### ISSUE TITLE
Configuring colors of PDF document

### ISSUE THREAD

**Issue by npistel** [ahrm/sioyek#112]
Any chance we'll see an option that allows us to configure the colors (background and font color) of the PDF document itself in the future?
Zathura for exmaple allows the user to do that (the image below shows the tutorial.pdf in Zathura with a color theme reminiscent of the Nord theme). Unfortunately I do not know how this is implemented in Zathura, so this might turn out to be very non-trivial.
![image](https://user-images.githubusercontent.com/53970966/144746985-26b9805d-f31c-467d-93eb-701c98b516b3.png)

**Comment by ahrm** [comment]
Added in 2c440ae598c0678e63b41c371138952368ee83c6. You can configure the colors in your `prefs_user.config` file using the following settings:
```
custom_background_color    0.18 0.20 0.25
custom_text_color    1.0 1.0 1.0
```
then you can use the `toggle_custom_color` command to turn this mode on/off. You can also add `toggle_custom_color` to your startup commands so that it is automatically executed on startup:
```
startup_commands		toggle_custom_color
```
![sioyek_custom_color](https://user-images.githubusercontent.com/6392321/144758495-d4f7f73f-eee8-47d4-88ab-6097c4343b44.png)
