### ISSUE TITLE
Page Pre-rendering

### ISSUE THREAD

**Issue by barrett-ruth** [ahrm/sioyek#1160]
Just discovered the `prerendered_page_count` setting which has *nearly* resolved all flickering (I set it to a reasonable value, nothing crazy).

The only problem I'm facing is near the rendering of *previous* pages while navigating. Specifically:

1. Zoom out a bit of a normal PDF (set `prerendered_page_count = 10` or something similar)
2. Press down arrow/j -> no flickering on the main pages or "bits" of the next pages appear at the bottom of sioyek.
3. Press up arrow/k -> the main pages themselves (i.e. centered page) will *not* flicker. However, the top of previous pages "peeking out" near the top border of sioyek *do* flicker.

I haven't set up video recording on my thinkpad, but LMK if you'd like me to create a video to reproduce. Should be a relatively simple setup though.

Can anything be done about this flickering?

**Comment by ahrm** [comment]
Is this on the main branch or the development branch?

**Comment by barrett-ruth** [comment]
Main

I am incredibly busy right now and would help otherwise but take a look at some repos like https://github.com/ibhagwan/fzf-lua. They have good ISSUE_TEMPLATE.mds and stuff like that, I notice this repo is barren. Could help to know installation method, OS, dev/main, etc.

**Comment by stites** [comment]
I think this issue can be closed -- there is no flickering in development. Here is a side-by-side render of sioyek (with no configuaration) and latexmk.

https://github.com/user-attachments/assets/137fce63-cb67-463f-95b3-b1dcd5ff3942

**Comment by stites** [comment]
This issue seems to be resolved in development. Below is a side-by-side screencast of a development sioyek (https://github.com/ahrm/sioyek/commit/d448ea962494cd2295669209320b667665314dc8) running next to latexmk, rendering a figure reference. There is no user configuration for sioyek (and I believe I correctly checked that my  `prerendered_page_count` was set back to 0).

https://github.com/user-attachments/assets/e8e85978-1c15-4bfb-8e39-003ee580917f
