### ISSUE TITLE
Multiple windows

### ISSUE THREAD

**Issue by borondics** [ahrm/sioyek#1187]
Hi, it seems that I can't open multiple documents at the same time in separate windows. While I appreciate the push for single-tasking, often it is necessary to quickly switch between documents. Is there a feature that missed my attention that allows this?

**Comment by atlasdune** [comment]
try Crtl-t

**Comment by dinesh-58** [comment]
I believe that can be done by adding this to your `prefs_user.config`:
```
should_launch_new_window    1
```
Though I'm currently facing a bug where if there are multiple sioyek windows open, switching to another sioyek window causes it to go black. Can you check if this happens for you? This has been fixed in the [version 3 alpha](https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0) but that may not be fully stable yet.

**Comment by borondics** [comment]
Thanks @dinesh-58! Works for me, even the switching between individual windows. I am on MacOS 14.6.1 using the latest sioyek 2.

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by dinesh-58** [comment]
> to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html) maybe this will solve your problem.

@ahrm seems like a spam reply. Haven't clicked on the link because I don't trust it. Could you delete this?

**Comment by ahrm** [comment]
Yes, please don't click on the link. Doesn't github have ability to ban a user and all their posts in a repo?

**Comment by dinesh-58** [comment]
This issue can be closed btw
