### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by kookma** [ahrm/sioyek#12]
I opened a 98k pdf and I opened Task Manager / Processes under Windows 10
It uses 296MB of memory! while this is only 96kB for Summatra!

Would you please have a look!

**Comment by ahrm** [comment]
The amount of memory we use has very little to do with the size of the PDF. Most of memory is used for cached page bitmaps. We do use more memory than Sumatra in general because we cache entire pages (we don't split the page into bands). So if you are very zoomed in (especially on a high resolution display) we do use a lot of memory for cached bitmaps. I could add an option to limit the size of cached bitmaps (currently it is hard-coded).

Could you please tell me the resolution of your display?

**Comment by linearcombination** [comment]
Love this app, thanks so much for making it. I too ran into a rather vicious memory leak on macOS Catalina 10.15.7. I've got 16gb of memory on my MBP and it has the distinction of the only app that has every exhausted all available memory and triggered macOS force quit dialogue. This was after leaving it running for maybe 40 minutes. I had my MBP display blacked out and was viewing on my EIZO Flexscan external monitor which has lower resolution (but awesome paper mode) than the MBP' s retina screen. Despite this this is the most promising PDF viewer I've seen in a while (typically I use Preview or pdf-tools inside Emacs which is also great), hope this can be fixed.

**Comment by analyticd** [comment]
Love this app. I too experienced a memory leak on macOS Catalina 10.15.7. I had it open for about 40 minutes and it caused the macOS emergency force quit dialog to appear as it had exhausted the majority of all 16gb of memory and created a memory exhaustion exception. Force quiting through the dialog restored system balance. I was using an MBP and had the brightness off of the internal display and was viewing on a lower resolution EIZO Flexscan monitor.

**Comment by analyticd** [comment]
Just a little bit more info: this happened after first trying all the features in the tutorial and then opening a few different PDFs. I wondered if perhaps a corner case was using the portal feature when the MBPs brightness was at zero. The portal opened on the EIZO monitor (both parts of the portal since the MBPs screen's brightness was set to zero). I thought perhaps this might touch on a weird corner case, just a thought. It has worked fine now after this initial experience with memory hovering around 250mb to 350mb-ish, so that is fine, similar to pdf-tools which also uses poppler.

**Comment by ahrm** [comment]
Thank you for you detailed feedback. I will try and see if I can reproduce the issue.

**Comment by wongsingfo** [comment]
Enjoy this app. The sioyek takes more than 1.5 GB memory after opening ~10 12-page documents. I noticed that the app takes additional ~150 MB memory every time a new document is opened. It is possible to add an option to limit the cache size and clear the cache for the least-recent-used document? Thanks in advance for your attention.

fyi, my display resolution is 3840 x 2160.

**Comment by ahrm** [comment]
Memory usage should be significantly improved after b2a88f152bf77ac976f0f4b26ee62b0e45e4d6ba and 2b8503de4fee2e7b6ef6972fc482b9a31a526a3e.
