### ISSUE TITLE
Highlights not visible in other apps

### ISSUE THREAD

**Issue by DOFfactory** [ahrm/sioyek#120]
So I marked up a document with sioyek, I open the resulting PDF in another app (in my instance Xodo desktop version, [https://pdf.online/?from=xodo](https://pdf.online/?from=xodo)), and the highlights are not visible. Reopening the PDF in sioyek shows the highlights. Also, PDFs highlighted in Xodo shows the highlights in sioyek. 

Is there some problem with the highlighting that is not standard across the PDF specification?

**Comment by DOFfactory** [comment]
Ah, I see, I was not aware of this. Does this mean that if I want to migrate the app and/or PDFs/notes, I need to move the database file with the app? Do you have any instructions for this?

**Comment by ahrm** [comment]
Yes, you just have to move your shared.db file across machines. You can do this manually or use file synch services such as dropbox to handle this automatically. See https://github.com/ahrm/sioyek/issues/29#issuecomment-915982417 for more information.

**Comment by DOFfactory** [comment]
Understood. Just to ideate further, do you think some sort of option into the settings could be introduced for another type of setup? I know the app itself is relatively small and one can upload the whole portable app folder itself to Dropbox. 

What I had in mind is, if you do not change the PDFs, the macOS app [Skim](https://skim-app.sourceforge.io/) is storing additional data next to `filename.pdf` of the PDF in a `filename.skim` file. This means that one can sync the folder with PDFs and these added files only, not the app. This also means that if one forgets to sync the `shared.db` from another machine, the highlights are still accessible by just simply installing sioyek on the machine. 

Do you think this would be something useful for others? A choice for this option might be made in the config file, for example, where the user can choose between a `shared.db` or `filename.ext` option.

**Comment by ahrm** [comment]
It does sound usefull, but I will only implement it if it can be done cleanly and without complicating the code too much (which is unlikely unfortunately).

**Comment by DOFfactory** [comment]
Cool, this sounds great. +1 question, is the v1.0.0 in the releases the latest? I have the feeling as if there were other updates, as if I am not using the latest version.

**Comment by ahrm** [comment]
No 1.0 is not the latest commit. Sometimes I create builds of newer commits in this repository:

https://github.com/hexomancer/sioyek/releases/tag/v0.31.128

**Comment by DOFfactory** [comment]
Yay! Thank you!

**Comment by DOFfactory** [comment]
Just double checking, so I should add `embed_annotations 1` or `embed_annotations true` in the `prefs_user.config` file, correct?

**Comment by ahrm** [comment]
> Just double checking, so I should add `embed_annotations 1` or `embed_annotations true` in the `prefs_user.config` file, correct?

No, you should open the file you want to export and then open command menu (`:` by default) and then type `embed_annotations` which asks you to specify a target file which will be the new file with annotations embedded.

**Comment by DOFfactory** [comment]
any chance setting this generally in the prefs file then? :-)

**Comment by ahrm** [comment]
> any chance setting this generally in the prefs file then? :-)

I think I did not explain the functionality of this feature properly. The pdf files created using this method are not meant to be used by sioyek itself (for example bookmarks and highlights are no longer searchable in these files).

The main purpose of this feature is to be able to share your highlights/bookmarks with someone who is not using sioyek or another computer which doesn't have sioyek installed, it is not an alternative way of storing bookmarks/highlights for sioyek itself.

So I don't know exactly what you mean by having an option in `prefs.config`. Do you mean automatically export to another file every time a new annotation is created in the PDF file? I don't think this is a good idea because exporting is a relatively heavy operation (exporting a large PDF files can take multiple seconds) and it would make sioyek unresponsive.

**Comment by DOFfactory** [comment]
I see now. My understanding is that your app tries to facilitate an easier reading of (academic) PDFs, and since there is no sioyek app for android for example, one is forced to read a possibly lengthy paper at the PC and then switch to tablet and so on. This means, it would be great to have the highlights exported as soon as one is reading it, and pick it up via any other app where left off. 

For example, there is an option in Xodo (another PDF reading app) where this setting can be enabled:
![image](https://user-images.githubusercontent.com/10846169/154493332-684b0ca2-2829-47d2-92d5-adfe50d82435.png)

I understand that this might not be trivial given the database used by sioyek, I am just sharing an experience of a practicing academic how I handle PDFs and try to feed back what would be desirable from my perspective

**Comment by DedZago** [comment]
> I added `embed_annotations` command in [263ae3a](https://github.com/ahrm/sioyek/commit/263ae3abf32705809ce08443570746fc781fb697) which exports a new version of the PDF file with all annotations embedded in file so that they are visible by other software.

I would like to chime in to report a problem and a possible extension for the `embed_annotations` command:
a) Using the `embed_annotations` command and overwriting the same file opened in the sioyek instance causes sioyek to crash on Linux.

b) I think adding an `embed_annotations_overwrite` command which embeds the annotations by overwriting the currently-opened file would save the trouble of searching for the same file each time. This would be useful for those (like me) who prefer working with embedded annotations "by default" in order to share them between other pdf readers.

Thank you for your work

**Comment by ahrm** [comment]
See https://github.com/ahrm/sioyek/issues/354 for a new way to embed annotations in the same file.
