### ISSUE TITLE
Off-by-one error when using next_item/previous_item

### ISSUE THREAD

**Issue by npistel** [ahrm/sioyek#121]
Prefixing the next_item command with a number makes Sioyek jump one search result too far. For example issuing 10n while at result 5 will jump to result 16, 1n will jump to 7 and so on. Similar thing with the previous_item command.

**Comment by ahrm** [comment]
While I understand this is a little counter-intuitive, this was by design. This is because we are counting from the next item not the current item. For example, otherwise `1n` would be the same thing as `n` and it would be redundant.

I did fix it in fe01081f0767085c5d67459c50b34a0149d30785 in the interest of being more intuitive though.
