### ISSUE TITLE
Escape closes everything

### ISSUE THREAD

**Issue by npistel** [ahrm/sioyek#123]
Not sure if this is intended behaviour and which features are all affected by this but if one presses Escape (for example to exit the command menu, close the current search, ...), everything that is affected by Escape will close, not just the last action (for which the Escape was most likely issued).
Extreme example: One could start a search, have link highlights enabled and a link overview opened. Opening the command menu and using escape to close it will also get rid of the current search, disable link highlights and close the link overview.
Would be a nice if Sioyek would instead only close the last thing which would be affected by escape.
On another note, I'm not sure if Escape should really affect toggle_highlight at all. It's a toggle after all (F1) and it's irritating when an accidental Escape toggles them off.

**Comment by ahrm** [comment]
Kind of fixed in 3c615ec73b2bacb886c7a869ea6d2d5ad5eb3ab3. Although it is not exactly what you asked for. Instead of cancelling the last action, we just see if overview page is opened and if it is, we just close it and do not proceed any further (we do the same thing with search). That is, instead of giving priority based on the time of the action, we give priority based on the type of the action.

A more principled approach would be to keep a list of actions and just pop the last one when performing escape but I think the current approach covers 99% of use-cases while being simpler. Please update the issue if you still have problems with this approach.
