### ISSUE TITLE
mac support?

### ISSUE THREAD

**Issue by okdistribute** [ahrm/sioyek#15]
How hard would it be to build for mac?

**Comment by ahrm** [comment]
> How hard would it be to build for mac?

It shouldn't be that hard because it already works in both windows and linux with the same codebase. Currently the only reason that there is no Mac build is because none of my computers is a mac so I can't build the mac version.

**Comment by amandasystems** [comment]
I looked at this just now, and I ran into some issues compiling. So what I did was installing qt5, harfbuzz, and GNU make using homebrew and making sure I had access to qmake (using `brew link --force qt`). Then I executed the installation script for Linux step by step by hand.

Compiling mupdf with the system HarfBuzz caused an error about not finding `hb.h` so I just removed the argument to use system harfbuzz. Then it compiled fine.

However, gmake:ing the main project caused an error I don't understand:
```
pdf_viewer/document.cpp:728:16: error: use of undeclared identifier 'PdfCharacterLocationData'
                        std::vector<PdfCharacterLocationData> location_data;
                                    ^
```

This is weird to me (not a C++ programmer) since PdfCharacterLocationData is not defined anywhere, and in fact that is the only use of it in the entire project.

**Comment by ahrm** [comment]
> I looked at this just now, and I ran into some issues compiling. So what I did was installing qt5, harfbuzz, and GNU make using homebrew and making sure I had access to qmake (using `brew link --force qt`). Then I executed the installation script for Linux step by step by hand.
> 
> Compiling mupdf with the system HarfBuzz caused an error about not finding `hb.h` so I just removed the argument to use system harfbuzz. Then it compiled fine.
> 
> However, gmake:ing the main project caused an error I don't understand:
> 
> ```
> pdf_viewer/document.cpp:728:16: error: use of undeclared identifier 'PdfCharacterLocationData'
>                         std::vector<PdfCharacterLocationData> location_data;
>                                     ^
> ```
> 
> This is weird to me (not a C++ programmer) since PdfCharacterLocationData is not defined anywhere, and in fact that is the only use of it in the entire project.

Oops. I should have deleted this line but it seems that I have forgotten to. It should be fixed in the latest commit.

However, note that Mac support is still extremely unstable. Even if you manage to build it you will probably encounter many bugs and crashes (mostly related to path issues). The main function that has to be fixed is `configure_paths` here: https://github.com/ahrm/sioyek/blob/d2608303e95081d88fad19dfbb796a484bb43eb5/pdf_viewer/main.cpp#L114

**Comment by amandasystems** [comment]
That looks very straightforward I fix though; from a quick glance you seem to be just putting everything in XDG_HOME which I guess would mean some application support directory on macOS. The rest of the code could in principle be shared between Mac and Linux.

**Comment by ahrm** [comment]
> That looks very straightforward to fix though; from a quick glance you seem to be just putting everything in `$XDG_HOME` which I guess would mean some application support directory on macOS. The rest of the code could in principle be shared between Mac and Linux.

Yeah it is probably very straightforward. The only problem is that I don't have a Mac computer to test this on. For all I know it might even work right now :D .

**Comment by ahrm** [comment]
I tested the mac version on a friend's laptop and it seems to work fine. Just run the `build_mac.sh` script to build the mac version. However, when I try to use `macdeployqt` in order to bundle the required libraries with the executable (i.e. uncomment the last two lines in `build_mac.sh`), the resulting executable crashes. I am not very experienced in mac development so I don't exactly know what I am doing wrong.
Anyway, if you are willing to build the project yourself, it seems to be working fine on Mac.

**Comment by amandasystems** [comment]
That sounds super cool, thanks! I'll try it and see what happens on my machine™.

**Comment by ahrm** [comment]
I have created an experimental Mac version using github actions. I was not able to test it on an actual machine tough. Theoretically it should work fine. Here it is:

https://github.com/hexomancer/sioyek/releases/download/mac93/sioyek-release-mac.zip

**Comment by OnceThenEver** [comment]
@ahrm I would be better to indicate whether it's for X86 or Apple Silicon.

**Comment by ahrm** [comment]
> @ahrm I would be better to indicate whether it's for X86 or Apple Silicon.

I build the mac version using github actions with `macos-latest` which I think uses x86 based macs (I am not sure though).

**Comment by Endle** [comment]
> > @ahrm I would be better to indicate whether it's for X86 or Apple Silicon.
> 
> I build the mac version using github actions with `macos-latest` which I think uses x86 based macs (I am not sure though).

Based on [this issue](https://github.com/actions/virtual-environments/issues/2187#issuecomment-737339211), I think Github Action only supports mac-intel yet (in 2021 Sept)

**Comment by okdistribute** [comment]
It worked on my silicon based mac. Good job! Thanks so much

**Comment by Kairotopos** [comment]
> I have added an official release with the Mac build here:
> 
> https://github.com/ahrm/sioyek/releases/tag/v0.31.6
> 
> (the minimum required Mac OS is still 10.15 though)

Bonjour. Could you build the sioyek for some lower version macOS, for example, the version macOS 10.12.6(I don't want to upgrade my macOS)? I have checked the conditions of building the app sioyek, and the necessary usage of tools, viz, Xcode and Qt 5, seems to be  somewhat difficult for my Mac system.
