### ISSUE TITLE
Support for Touch Screens

### ISSUE THREAD

**Issue by iamkroot** [ahrm/sioyek#16]
First, thanks a lot for this amazing piece of software! It really outshines other viewers for consuming papers/textbooks.

I wanted to put in a feature request for supporting scrolling with touch drags. Currently, if I drag on the touch screen, it simply behaves the same as mouse dragging with left button clicked - selecting all the text in those parts.

This is how the Edge browser (and Android touchscreens) behaves:
1. "Simple drags" scroll the document,
2. "Long presses" select the word under the finger (in sioyek, it currently acts as right click), and give handles which can be dragged to extend the selection.
	* This seems difficult to implement (especially the handles), so as a first approximation, we could instead do what the current "simple drag" does - after long press, until finger is lifted, select all the text that is dragged over.
3. "Two-finger press" acts as right click

**Comment by ahrm** [comment]
I added the ability to enable "drag mode" in 15cfbc61e95931d99239ea1bce083917137afa42 . You can press a shortcut (`<F6>` by default) to toggle drag mode and while in drag mode, instead of selecting text we drag the document along with mouse cursor. Here is an experimental build of this commit:

https://github.com/hexomancer/sioyek/releases/tag/v0.31.75

I don't plan to support the long press for text selection because it is too "touch screeny". I realize there are a lot of things that I could do for better touch screen support (for example pinch to zoom) however, this PDF reader is currently focused on keyboard users. I completely agree that a similar viewer with touch screen support is very valuable  (and it is something that I may do some day) but I would rather implement a touch screen version of this viewer from scratch with touch screen in mind because a good user interface for touch screen is completely different than a good user interface for keyboard users.

**Comment by iamkroot** [comment]
Wow, thanks for the rapid response! I tried out the build, and it feels decent. The drag mode is working great, but dragging with touchscreen still feels a bit weird, mainly because there is no "overscroll" - it stops scrolling as soon as finger is lifted. Generally, touchscreen UIs use the acceleration of the flick to determine the amount of overscroll and elasticity (deceleration), which gives it a bit of smoothness.

But I think this much should be enough for now, and I agree that more comprehensive touch screen support is overkill at this stage. For me, most of the time spent interacting with the touchscreen is to drag the page (since it feels more natural than a touchpad/mouse). I can simply fall back to keyboard/mouse when I need the other features of this app.

So thanks again for your effort. You can go ahead and close the issue if you wish.

PS: I noticed that scrolling with my touchpad does give overscroll in the app, but I guess that is coming from QT itself?

**Comment by ahrm** [comment]
> PS: I noticed that scrolling with my touchpad does give overscroll in the app, but I guess that is coming from QT itself?

I think so.
