### ISSUE TITLE
[BUG] Background is translucent (?)

### ISSUE THREAD

**Issue by iamkroot** [ahrm/sioyek#18]
On Linux, I have transparency+blur enabled on my compositor (OpenGL+KDE), and looks like sioyek also uses those values for the background. This is what happens when I enable dark mode:

![Dark mode bg blur](https://user-images.githubusercontent.com/29517049/128589790-eb4f0ae9-a409-48f5-b5f3-bada41b475e3.png)
(this looks pretty cool, to be honest)

There are some other rendering bugs too, probably related:

![Washed out](https://user-images.githubusercontent.com/29517049/128589822-1813b4b1-13e1-41c6-9f0d-432d4704c0b0.png)
dark mode disabled, nothing visible

![Nothing visible](https://user-images.githubusercontent.com/29517049/128589858-30cd2bb2-e4e8-4a4d-b6ee-2a188cfac88a.png)
this is an artifact of the screenshot app, much more was visible on screen

**Comment by iamkroot** [comment]
@ahrm I know this is a pretty weird bug, and I'd be happy to try to fix this myself. I have decent C++/OpenGL knowledge so I can at least give it a shot. Could you please give some pointers on where I should begin though?

**Comment by ahrm** [comment]
Hi!
The reason that I have not fixed this issue is because I have not been able to reproduce this issue.
This is the shader responsible for drawing PDF documents:
https://github.com/ahrm/sioyek/blob/1133218fe67a23a366673d6b2052148e5afeecc1/pdf_viewer/shaders/simple.fragment#L1

As you can see this is probably the simplest possible shader and it is unlikely that it contains any bugs. The only thing that I can think of is to output a `vec4` color instead of `vec3` maybe that will fix the problem?

This is the function that renders a page:
https://github.com/ahrm/sioyek/blob/1133218fe67a23a366673d6b2052148e5afeecc1/pdf_viewer/pdf_view_opengl_widget.cpp#L344

Please tell me if there is any other thing I can help you with.
Good Luck.

**Comment by iamkroot** [comment]
Ok so I narrowed down the source to https://github.com/tsujan/Kvantum app that I have installed to enable blur/transparency. I added a rule for it to use the default (non-blur) theme with sioyek and the rendering issues disappeared. I'd like to figure out _why_ the bug is really happening, but for now I'm fine with this workaround.
