### ISSUE TITLE
Better navigation of zoomed-in text, especially documents with two columns

### ISSUE THREAD

**Issue by efficacy** [ahrm/sioyek#185]
While I think it is an archaic way to do things, we can't escape the fact that many academic papers are formatted in two columns. This not only makes it difficult for a reader, who has to scroll down to the bottom of a page, then up to the top again to read the next column, but causes serious problems with small or low-resolution screens.

Usually when reading with Sioyek I automatically hit F10 to fit the text to the window, but for two column text this is often still not big enough, so I need to zoom in further. Unfortunately, Sioyek always seems to zoom to the horizontal centre of the page, cutting off lots of important information.  That would be just about bearable (although not ideal) if there were a way to scroll, slide, or drag the document horizontally, but so far I have not been able to find a way to do that.

Please consider:
1. some easy way to move around a zoomed-in document
2. better support for two-column text, such as a bindable command to go to the next or previous column in addition to navigating by page.

I hit this problem today when trying to read this article from 2022: https://www.sciencedirect.com/science/article/pii/S266665962200004X - It's open access, so feel free to use it as a test case!

**Comment by joaocarvalhoopen** [comment]
This is not a solution, but you can use Ctrl and mouse wheel to zoom in and out in a fast way where ever you like in the page.

Best regards,
João

**Comment by joaocarvalhoopen** [comment]
I tested it and you are right, the mouse point will not refocus the zoom.
I thinked it would refocus, you have to use the arrow keys with the mouse wheel and that is dificult.

Best regards,
João

**Comment by efficacy** [comment]
OK, so shift + scroll-wheel moves the text sideways, which is a great help. Sadly, this is not mentioned anywhere in the tutorial file or the online documentation :(

**Comment by joaocarvalhoopen** [comment]
Yes, I think the documentation is a little behind the features, but many features are also in just the build releases and Ahrm is making an incredible work at implementing the features from this App in record time. Regarding the feature of this issue, if he changes the center point of a zoom by just regarding where is the current mouse pointer position so that one can zoom in and zoom out with Ctrl + mouse wheel the current problem is resolved in what I think is a simple to implement way. And a really good implementation of the feature!

Best regards,
João

**Comment by ahrm** [comment]
You are right, the documentation is outdated. Mainly because I have been lazy since it is much more fun to code than to update the documentation ;) . One of these days I will suck it up and update the documentation.

I added the ability to zoom on the mouse cursor in the recent commits. By default it is disabled but you can enable it by adding this to your `prefs_user.config`:
```
wheel_zoom_on_cursor 1
```
I have also added the following command which allow you to quickly jump to the left and right side of document: `goto_left`, `goto_right`, `goto_left_smart`, `goto_right_smart`. The difference with the smart versions is that they ignore white page margins. I have added the following keybindings to my `keys_user.config`:
```
goto_left 0
goto_right <S-)>
goto_left_smart <S-^>
goto_right_smart <S-$>
```

**Comment by joaocarvalhoopen** [comment]
Good morning Ahrm,
I tested the feature with the last build version in Linux Ubuntu 20.04 and added the flag wheel_zoom_on_cursor 1, **but it always ZOOM with it’s reference to the center of the screen and not to the cursor position of the mouse pointer position.** So I think it's not working as you intended at least in Linux Ubuntu 20.04 

Thank you,

The very best regards,
João

**Comment by ahrm** [comment]
> Good morning Ahrm, I tested the feature with the last build version in Linux Ubuntu 20.04 and added the flag wheel_zoom_on_cursor 1, **but it always ZOOM's in with it’s reference to the center of the screen and not to the cursor position of the mouse pointer position.** So I think it's not working as you intended at least in Linux Ubuntu 20.04
> 
> Thank you,
> 
> The very best regards, João

There was no build with these latest commits available. I issued a build request to create a prerelease build. If there are no issues a new build should be available in this repository in about 20 minutes.
https://github.com/hexomancer/sioyek/

**Comment by ahrm** [comment]
It is available now here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.218

**Comment by joaocarvalhoopen** [comment]
Hello Ahrm, I tested the Zoom to the pointer, and tested all the 4 shortkeys functionality with the PDF that @efficacy supplied and they all work correctly in Linux Ubuntu 20.04 .

Thank you very much and nice work!

I will update my configuration files for Dyslexic people.

The very best regards,
João

**Comment by joaocarvalhoopen** [comment]
This are **my Configurations for Dyslexic people**.
https://github.com/ahrm/sioyek/discussions/182

**Comment by ahrm** [comment]
By the way in new commits of sioyek we handle two column documents in visual scroll mode. We initially highlight the first column and then jump to the second column.

**Comment by joaocarvalhoopen** [comment]
Hello Ahrm,

I have to experiment it :-)
Thank you for the incredible work you have being put on Sioyek!

The very best regards,
João
