### ISSUE TITLE
[Feature Request] Ranged search for highlight search/other improvements for highlight search

### ISSUE THREAD

**Issue by mrro22** [ahrm/sioyek#195]
Thanks so much for this awesome tool! Already become my primary PDF reader. I especially love the highlight searching feature. 

Two quick ideas for potential improvement on highlight searching: 

1. ranged search through highlights, similar to how Sioyek's ranged search feature already works. My primary use case for the highlight search feature isn't searching through the entire book for highlights in x register (though this is sometimes useful), but rather searching through the current chapter. 

2. A way to tab through the highlight blocks for a given highlight register. The highlighting feature is awesome to the extent it allows me to have quick access to all text I've classified as belonging in x register. Tabbing through the highlighted blocks would be a great way to make finding nearby related text lightning fast.

Again, thanks so much for this fantastic piece of software

**Comment by ahrm** [comment]
I added the ability to jump to the next and previous highlights in 7396e0f1efc05a67779d754ac5764da709164f3c. Here is the relevant commands in my `keys_user.config`:
```
goto_next_highlight gnh
goto_prev_highlight gph
goto_next_highlight_of_type gnt
goto_prev_highlight_of_type gpt
```
`goto_next_highlight_of_type` jumps to the next highlight with the current selected highlight type. You can change the selected highlight type using `set_select_highlight_type` command.

I think ranged highlight search is a little too niche and it probably wouldn't work very well either because in ranged search we use the lower most item in table of contents tree, which doesn't necessarily correspond to the current chapter (it might be a subchapter or a sub subchapter, depending on the book ). Anyway, the point is that its behavior is too unpredictable to be reliably used and therefore I won't implement it.

But I added the following features in 2796a3e4ae5e67af7365ffa5b1947132c6801434 which I think should help with your problem:
* We now show the page numbers next to highlight entries
* We automatically select the closest highlight to the current position

**Comment by mrro22** [comment]
Works like a charm. Thanks for your quick work and this amazing software!
