### ISSUE TITLE
not an issue - future roadmap

### ISSUE THREAD

**Issue by johndpope** [ahrm/sioyek#2]
**1st Steps**
There's projects that have made commenting on pdf a business. I need to dig up the link.
I think one step you could explore (not immediately on a rainy day) - is to show a list of what people are reading using opt in telemetry data - maybe using google sheet - something simple that you could set and forget without too much overhead - and then come back in 12 months and be like - let's take another step -
you might find it catches on - and you could have millions of users.
it would take a sign in process - a backend - maybe just firebase. and then a simple post to a worksheet.

I browse papers all the time - I gravitate to youtube to get help reading them as the linear algebra is quite advanced.
There's an opportunity to connect people - with papers - and have them help each other. But first step would be take a look at the data / and make it public from the outset.  (you wouldn't want to expose emails / but you could just have a list of papers...)

**Comment by ahrm** [comment]
I think this is an interesting idea. For example another similar idea would be to connect the portals of people who are reading a document with the same hash. For example one person could annotate a PDF document by connecting the relevant parts or even adding portals to external relevant documents and when others are viewing the document, portals that are relevant to their place in the document can be pulled from the internet and shown to them, kind of like an MMO PDF reader!

While I think this is very interesting, there are many problems:

* I don't think users will be happy with (even optional) telemetry.
* While very interesting in theory, I doubt it works as well in practice because it would need a lot more users than we currently have to be really useful.

**Comment by johndpope** [comment]
I completely agree with needing lots of users - but consider the genisis for facebook that propelled it   was getting critical mass in the schools and universities. 
Consider a class of students willingly using this software - and solving / understanding a single paper as the testimonial for this to be more useful. You don't need millions of users for this to pathway to be a huge success.
You've got a whole class of students to read a white paper - every where students get stuck
 - they could have a link to a github gist / youtube link with relevant content. 
 
With firebase - it's easy to branch off to use messaging. 
https://firebase.google.com/docs/cloud-messaging/cpp/client
and being open source - could provide opportunities for devs to come join the party of development (and they would do the work with your oversight).

**Comment by DhruvaSambrani** [comment]
While I love the idea, I disagree on the implementation. Instead of baking in the collaborative tools into the app, we should instead use preexisting mechanisms for collaboration. By simply making the "annotations" file human editable and hence git-able, most workflows would be immediately solved.

1. Parallel annotators, such as in a group, come together to merge their findings via git.
2. A simpler constantly syncd mechanism via Dropbox/GDrive/Syncthing/something else. For this, the annotation file should not be locked by the app.
3. Sharing "notes". By adding a non-annotation syntax to the annotation file, what we basically have is a full on note-PDF linking. This is immensely useful while studying.

**Comment by johndpope** [comment]
@ DhruvaSambrani you're not just right.....you're damn right. how do we do it?

**Comment by dtantono** [comment]
I wish we can add image/ write something with this app and package it in .deb format.

**Comment by nbCloud91** [comment]
If I may suggest something as a user, I agree with current direction of sioyek, it is best as a PDF reader with local annotations (also thanks for not embedding them by default).
For collaborative annotations many academic/research groups use hypothes.is which is particularly tailored for such use case. It can even be self-hosted, the backend and client are both open source. I think such functionality as collaborative annotations should be made using open-standards and outsourced to dedicated services, for interoperability some plugins to interact with those API can be made. For example to pull in hypothes.is annotations or to push local annotations made on sioyek to hypothes.is

**Comment by johndpope** [comment]
looks like hypothes.is very strong candidate for integraiton.
I'm closing this ticket in favour of my next brain wave idea 
https://github.com/ahrm/sioyek/issues/600
