### ISSUE TITLE
Sioyek 1.2 Issues on MacOS (Macbook Pro M1)

### ISSUE THREAD

**Issue by mbennette68** [ahrm/sioyek#205]
Sioyek 1.2 does not seem to function correctly on MacBook Pro M1 Monterey.

When I start the app it just freezes, displays white background and does not respond to 
commands (e.g. can't open files).

Earlier version of Sioyek (1.1.0) works just fine except for DarkMode issue that changes the color of images within PDF docs as well as the fact that after first use, the app loses track of the Tutorial PDF that it comes with and opens up at 
first startup.

**Comment by ahrm** [comment]
Sorry, I don't have a mac computer and because of this mac-related issues take a long time to fix. I did some random changes to mac builds and made an experimental build here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.300. One of my friends who has a mac confirms that this build works but I haven't tested it myself.

**Comment by ahrm** [comment]
> 

I tried that but it was way too slow.

**Comment by mbennette68** [comment]
> > 
> 
> I tried that but it was way too slow.

Ok, I see.

Just in case you are exploring alternatives to that, there might be another option such as running MacOS on Azure Cloud and logging in via RDP.

The following link will point you to an Udemy tutorial on how this can be done:
[Running MacOS in Azure VM](https://www.udemy.com/course/install-macos-on-azure-virtual-machine/) 

Thank you for the reply 👍

**Comment by SichangHe** [comment]
You might consider [the docker image](https://github.com/sickcodes/Docker-OSX)
