### ISSUE TITLE
[Feature Request] Arbitrarily many registers

### ISSUE THREAD

**Issue by mrro22** [ahrm/sioyek#221]
I know this one might be kind of a doozy, but would it be possible to allow users to create arbitrarily many registers (perhaps the user could define them in the prefs.config)? i.e. creating highlight registers aa, ab, ac, and so on? I assume this is a niche usage as 26 is already too many for virtually everyone. However, as a student I like to create registers for themes as I go along. Sometimes these themes turn out to be pretty minor and I've sort of "wasted" a register. Of course I could have multiple themes share a register, but ideally I would be able to create my own.

I'm sure this one is annoying to do, so no worries if it can't happen. You're the best, ahrm!

**Comment by ahrm** [comment]
As you said, this is probably too niche and requires a complete rewrite of the mark system, so I don't think I will implement this. As an alternative what you could do is to have multiple `prefs_user.config` files with different themes and swap them using a shortcut (you could use your window manager or sioyek's built in `execute` command). Also you could use a lower priority `prefs_user.config` file only for colors so that you don't have to change all these files every time you change other configs.

**Comment by mrro22** [comment]
No worries, makes sense. I like your suggestion anyways!
