### ISSUE TITLE
Build fails on Linux for version 1.3.0

### ISSUE THREAD

**Issue by goggle** [ahrm/sioyek#229]
I'm trying to update my `aur` package to version 1.3.0, but unfortunately the build fails.
Here is the output:

[build_linux_output.txt](https://github.com/ahrm/sioyek/files/8694150/build_linux_output.txt)

It used to work for version 1.2.0.

**Comment by ahrm** [comment]
Strange, because the error seems to be because of `std::strcmp` function in `utils.cpp` and we definitely had this line in `1.2.0` as well. Anyway, in e76aa69f393df0649f70e4de428f3ab094e9557c I manually included `cstring` which should resolve the issue. I am not entirely sure though because I was not able to reproduce the issue in the first place.

**Comment by goggle** [comment]
Thanks, this fixes the issue.
Do you release a version 1.3.1 with https://github.com/ahrm/sioyek/commit/e76aa69f393df0649f70e4de428f3ab094e9557c included or is this not planned?

**Comment by ahrm** [comment]
It is not planned.
