### ISSUE TITLE
Cross page text selection (select text on two pages)

### ISSUE THREAD

**Issue by shenlebantongying** [ahrm/sioyek#239]
Sioyek cannot select beyond a page's end or across multiple pages. 

Here is a simple comparison:

In sioyek:
<img src="https://user-images.githubusercontent.com/20123683/169679288-54b75bd2-34ab-4cbf-a199-57bbccf1ad49.png"  width="200"/>

In GNOME Documents
<img src="https://user-images.githubusercontent.com/20123683/169679320-6daaa96b-0cd2-48c6-bac5-120e0708bab3.png"  width="200"/>

**Comment by ahrm** [comment]
Should be fixed in 6729b0b85e712b10a4d15eb049256f466655ce9d. However, note that if you highlight the selected text ([highlights](https://github.com/ahrm/sioyek#highlights) feature) because of the way that highlights is implemented, only the highlights of the first page will be shown. Fixing this would be a little complicated and I think is not worth it because cross-page highlights are very rare.

**Comment by shenlebantongying** [comment]
I tried to fix and can confirm selection works.
