### ISSUE TITLE
Fastread doesn't work on Mac

### ISSUE THREAD

**Issue by hovnatan** [ahrm/sioyek#245]
I run the server `summary_highlight_server.py` then `toggle_fastread` but the Flask server doesn't get the command. I have `enable_experimental_features 1` in prefs. Thanks!

**Comment by ahrm** [comment]
Do you use the exact sioyek version mentioned in this blog post? https://ahrm.github.io/jekyll/update/2022/04/14/using-languge-models-to-read-faster.html . I have since removed the server capabilities since that version because it was just an experiment and I didn't plan to maintain it (also it didn't make sense to run a full-fledged language server just for highlights).
We do still have basic bionic highlighting though.

**Comment by jparr721** [comment]
Hi ahrm, 

I also recently installed this and am finding that it also does not work for me even when attempting to use the basic :toggle_fastread command as specified in the documentation. I also have the experimental features enabled and I am running sioyek 1.3.0.

**Comment by ahrm** [comment]
Sorry, my bad. I forgot to mention that you need to also add this to your `prefs_user.config`:
```
use_heuristic_if_text_summary_not_available 1
```

**Comment by jparr721** [comment]
Ah yes, that worked like a charm! Thank you! For context, I was reading this: https://news.ycombinator.com/item?id=31475420 thread on hacker news to determine the right configs to use.

**Comment by hovnatan** [comment]
Thanks!
