### ISSUE TITLE
sioyek cannot read a file named `k&r.pdf` correctly and gives blank page

### ISSUE THREAD

**Issue by SichangHe** [ahrm/sioyek#257]
## result

The page is completely blank and the "mode line" at the bottom left says `Page 0 / 0 [ h:a ]`

## steps to reproduce

On macOS 12.0.1 with sioyek 1.32.25 on M1

1. At the `~/Downloads` folder, download the C book:

```shell
curl -LO https://kremlin.cc/k\&r.pdf
```

And its name would automatically become `k&r.pdf`

2. Use sioyek to open this file

## remarks

- I can open this file without problem with `Preview` or `Skim`
- sioyek opens the file correctly after I renamed the file `The C Programming Language, Second Edition, Brian W. Kernighan & Dennis M. Ritchie @AT&T Bell Laboratories.pdf`
- The problem seems to happen only on this specific pdf. I renamed another pdf to `k&r.pdf`, but sioyek opened it correctly. But, it seems that I have opened that one pdf before. I then tried another pdf that I haven't used sioyek to open before, and sioyek also opened it correctly.

**Comment by ahrm** [comment]
I was not able to reproduce the issue. Is the issue reproducible on your machine? In order to reset sioyek's database, you can first back up `local.db` and `shared.db` files and then delete them (this will remove all of your data within sioyek, including marks, bookmarks, etc. and list of previously opened documents, of course you can restore this data by restoring your backed up `local.db` and `shared.db`).

**Comment by SichangHe** [comment]
Unfortunately, I wasn't able to reproduce the issue on my machine either using current database or reset.
This makes it extremely hard to debug…
