### ISSUE TITLE
Windows title bar ignores night mode and stays white (in windowed mode)

### ISSUE THREAD

**Issue by 205g0** [ahrm/sioyek#3]
Pretty much the title. Or it would be also great to let the color be configured manually.

**Comment by ahrm** [comment]
As far as I know there is no clean and simple way to do this (though I would love to be proven wrong). The reason is that our application doesn't even draw the titlebar, it is done by windows so we have very little control over it.

I'm not an expert on the subject but I think only UWP applications can automatically adjust their titlebars in Dark Mode. For example even Window's own notepad or other PDF readers like Sumatra PDF can't adjust to Dark Mode.

I will still try to find some way around it because it is clearly possible (for example chrome does it) but in the meantime I suggest doing the following: 

Enable showing accent colors on Title bars and windows borders and the manually set the accent color to whatever you want:

![titlebar](https://user-images.githubusercontent.com/6392321/126610264-fc624a05-b9ff-4b8c-8ec0-42d715fa48ce.png)

**Comment by amzon-ex** [comment]
@ahrm Does [this thread](https://github.com/microsoft/microsoft-ui-xaml/issues/2484) provide any insight/recent developments on how to do this?

**Comment by ahrm** [comment]
Thanks but I don't think that helps much. We don't use windows API directly, we only use qt. So it will only be fixed if qt implements this.

**Comment by amzon-ex** [comment]
Thanks, @ahrm ! When can we expect a release? It's been a while!

**Comment by ahrm** [comment]
I don't have a specific time in mind, hopefully not too long but I am not making a promise :) .
