### ISSUE TITLE
If a file has changed location and sioyek can't find it, you can't open the next file either

### ISSUE THREAD

**Issue by mutachre** [ahrm/sioyek#312]
Macbook M1 here on Monterey. I think it is a bug (rather annoying): if I move a file (I usually move them in my reference manager - I tried with epub, but I think with pdf it is the same) and afterwards I try to open a new file sioyek gives me this error.. How is that? 

<img width="904" alt="Schermata 2022-07-10 alle 14 24 01" src="https://user-images.githubusercontent.com/62408551/178145353-58fce510-784f-4d90-a9e2-d83cdaa61efc.png">

Thank you.

**Comment by ahrm** [comment]
How are you opening the new file? If you open it from command line like this:
`sioyek new_file.pdf` there should be no error. If you are trying to open sioyek and then open the new file, it does display this error because it is trying to open the last opened file (which has since been moved), you can just press okay and open the new file as you would normally. Is this method not working for you?

**Comment by ahrm** [comment]
Should I close this issue?
