### ISSUE TITLE
Vimtex integration may be broken

### ISSUE THREAD

**Issue by ejuarezg** [ahrm/sioyek#326]
Hi, really enjoying sioyek for my research.

I came across the issue of broken vimtex integration when I updated to 1.4.0 AppImage from 1.3.0. My vimtex configuration of `let g:vimtex_view_method='sioyek'` leads to a black screen in sioyek when rendering the pdf. As a workaround, I am instead now using
```
let g:vimtex_view_method='general'
let g:vimtex_view_general_viewer='sioyek'
```
which works fine.

Please let me know how I can help you debug this issue. Thanks!

**Comment by ahrm** [comment]
I was not able to reproduce this issue with my Vimtex installation on windows. Maybe it is an OS-specific issue?

**Comment by ejuarezg** [comment]
It may very well be. I'm running PopOs! 22.04 and neovim. I'll look into how to debug neovim and see if gives any useful information on what may be going on.

**Comment by t4y** [comment]
Seeing the same issue here on Ubuntu 22.04 with nvim and the sioyek 1.4.0 appimage.
My init.vim has
```
let g:vimtex_view_method='sioyek'
let g:vimtex_view_sioyek_exe='/home/t4y/appimages/Sioyek.AppImage'
```
but using the vimtex liveview causes Sioyek to open as a black screen. The workaround in the op works but does not allow the inverse_search to be used on right click.

**Comment by ejuarezg** [comment]
For what it's worth, I've not had any issues in a while. What may have solved it was installing the dependencies sioyek requires to build from source code. Maybe it's an issue with the AppImage not finding the correct system libraries, though that's just completely guessing and is probably wrong.

**Comment by t4y** [comment]
I tried installing the dependencies and building from source. The AppImage still exhibits the same behavior: Sioyek works, but the vimtex integration is borked since it opens on a black screen.

I also tried the manually build Sioyek, and its vimtex integration does not work either. @ahrm there definitely seems to be an issue here, although I can't say what causes it.

I'll be manually opening the pdf file in the meantime to use the vimtex inverse search because it's a really convenient feature.

**Comment by ahrm** [comment]
I tried this exact setup on an ubuntu 21.04 laptop:
```
let g:vimtex_view_method='sioyek'
let g:vimtex_view_sioyek_exe='/home/t4y/appimages/Sioyek.AppImage'
```
and could not reproduce the issue. Are you using the latest version of vimtex?

**Comment by t4y** [comment]
I installed vimtex via vim-plug, the behavior I described above was encountered with the last pull being sometime in June. I tried again with a fresh pull right now and still have the same issue: starting the vimtex liveview from nvim starts sioyek with a black window.

I also tried running nvim without any plugins besides vimtex and tried running vim instead of nvim: still the same issue.

Do you know if there's a way I can see logs somehow, or is there any other info I can provide? I'm not sure how to troubleshoot this.

**Comment by ahrm** [comment]
What is vimtex liveview? Do you mean `VimtexView` command or are you using some sort of live updating plugin?

**Comment by t4y** [comment]
Oh I mean the `<local-leader>ll` (`vimtex-compile`) command and `<local-leader>lv` (`vimtex-view`) command yes.

**Comment by ahrm** [comment]
Maybe there is a problem with the filesystem paths? Can you share a minimal latex example where you have this error along with the exact path of the latex files on your filesystem?

**Comment by t4y** [comment]
I don't know why I didn't think of trying that earlier, I had been troubleshooting with a rather complex document all this time. 

I tried a minimal example, just a single `.tex` file with a simple article and sure enough it works. The other project does work with vimtex + zathura though.

One thing I noticed is that the document where I get the black screen has a lot of commands and lines before the document actually starts. I've noticed that when I hit `\ll` (`vimtex-compile`) while my cursor is on the first line I get the black screen, when I then move it down to some place after `\begin{document}` and hit `\lv`, sioyek shows the document! And sure enough, if I open the `.tex` file, move the cursor after `\begin{document}` and hit `\ll`, no black screen, the sioyek vimtex integration works like a charm!

A simple example that reproduces the issue for me is the following file:

```
\documentclass[11pt]{article}

%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%
%

\begin{document}

\title{My Article}
\author{Nobody Jr.}
\date{Today}
\maketitle

Blablabla said Nobody 

\end{document}
```

Also maybe helpful is the filesystem layout after creating the `test.tex` file, writing the example above in nvim and hitting `\ll`, observing the black screen and then quitting:
```
.
├── .build
│   ├── test.aux
│   ├── test.fdb_latexmk
│   ├── test.fls
│   ├── test.log
│   ├── test.pdf
│   └── test.synctex.gz
└── test.tex
```
which looks like that because I set `$out_dir = '.build';` in my `.latexmkrc`.

--- 

So for me the solution seems to be to only start `vimtex-compile` after moving my cursor to further down in the document, which I can absolutely live with. I'm definitely curious if all of this is just an issue on my end though or if you'll be able to reproduce it with the example I gave.

**Comment by ahrm** [comment]
I was able to reproduce the issue. The problem was that when the cursor was on those parts of the document, synctex forward search would fail (because there was no place in the PDF file corresponding to those parts), and previously we did nothing when it failed. I changed it in 5ae0e5143fbbbe6130ad67d5858ab58b2bd6087f so that we open the document now.
