### ISSUE TITLE
Double click for word selecting.

### ISSUE THREAD

**Issue by x-challenger** [ahrm/sioyek#34]
This is a useful tool. Could you add the function for which we can double click left mouse to select the single word or tell me how can I do about it.

**Comment by ahrm** [comment]
We already have this feature, you just have to move  the mouse a little bit after double clicking to initiate selection.

**Comment by x-challenger** [comment]
Thanks, I have try it and got your point after your reply. But maybe it will be more convenient if it can be done just double click rather than with a little bit moving of mouse(maybe this  will conflict with your existing functionalities? just as a suggestion)

**Comment by ahrm** [comment]
I significantly reduced the minimum distance needed for highlight mode to be activated in d3a46ce6496ab4ae2c6b3e47744a1595a0b09c3a . There is still a small distance you need to move before it is activated because I want to reserve double click for more useful actions (for example maybe instead of middle clicking with mouse we could use double click for smart jumps which probably is very useful for laptop users).
