### ISSUE TITLE
[Bug] shell command's page number expansion %4 should start from 1

### ISSUE THREAD

**Issue by chaoyi** [ahrm/sioyek#350]
Currently it's starting from 0.  Starting from 1 is more consistent with `--page` option.

**Comment by ahrm** [comment]
While I understand your point about consistency with `--page` option, I think I will keep the current convention mainly to maintain compatibility with existing scripts.. Usually in the programmer-side of things, we use zero-based indexing and in the user-side we use one-based indexing. Since scripting is more of a programmer thing I don't think using a zero-based indexing is a bug issue.

**Comment by chaoyi** [comment]
I still think `%4` should start from 1.  Because `%4` is used as a command line argument input to another program (or a user script), and most programs use 1-based indexing, it's more convenient that way.  For example, I can just configure sioyek to open in zathura via `new_command _open_file_in_zathura zathura -P %4 %1`.
