### ISSUE TITLE
[Feature Request]: Support URL Scheme

### ISSUE THREAD

**Issue by windily-cloud** [ahrm/sioyek#352]
If I click on the link `sioyek://filepath=xxx.pdf&page=32`, sioyek will open xxx.pdf and jump to page 32.

This way I can get a link to the corresponding page number through a custom command to create a link to the pdf in plain text notes.

If  tycoon has any better ideas, please tell me. I really like how you made such an elegant software. Thank you very much for any replies.😊

**Comment by ahrm** [comment]
I don't think I can add this to sioyek itself because doing this in a cross-platform way is not very straightforward (it is an OS-dependent configuration). But you can easily configure it yourself. For example I used these two scripts to configure it on windows (probably there are analogous configurations for other operating systems).

First I created a proxy script that parses the url and calls sioyek with the correct command line arguments (`sioyek_proxy.py`):

```py
import sys
import subprocess
import urllib
import urllib.parse

SIOYEK_PATH = r'C:\Users\Lion\source\repos\pdf viewer\Debug\sioyek.exe'

if __name__ == '__main__':
	url = sys.argv[1]

	if url[-1] == '/':
		url = url[:-1]

	if url.startswith('sioyek://'):
		url = url[len('sioyek://'):]
		sep_index = url.rfind('&')
		file_part = url[:sep_index]
		page_part = url[sep_index + 1:]


		file_name = file_part[len('filepath='):]
		page_number = page_part[len('page='):]
		file_name = urllib.parse.unquote(file_name)

		subprocess.run([SIOYEK_PATH, file_name, '--page', page_number])
```

and then registered the `sioyek` protocol to this script:

```
REGEDIT4

[HKEY_CLASSES_ROOT\Sioyek]
@="URL:Sioyek Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\Sioyek\DefaultIcon]
@="\"C:\\Users\\Lion\\source\\repos\\pdf viewer\\Debug\\sioyek.exe\""

[HKEY_CLASSES_ROOT\Sioyek\shell]

[HKEY_CLASSES_ROOT\Sioyek\shell\open]

[HKEY_CLASSES_ROOT\Sioyek\shell\open\command]
@="\"C:\\Users\\Lion\\AppData\\Local\\Programs\\Python\\Python37\\python.exe\" \"D:\\labs2\\protocol\\sioyek_proxy.py\" \"%1\""
```

**Comment by windily-cloud** [comment]
Thank you very much！！！ Orz ！

**Comment by temberature** [comment]
applescript like this

on open location schemeUrl

Info.plist
<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>Sioyek Scheme</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>sioyek</string>
			</array>
		</dict>
	</array>
