### ISSUE TITLE
Support spaces in execute

### ISSUE THREAD

**Issue by mreppen** [ahrm/sioyek#371]
It appears it is not possible to execute with an argument containing a space. For instance `execute notify-send "A B C"` executes `notify-send` with arguments `"A`, `B`, and `C"` when the expected argument is `A B C` (since 2 arguments are expected, it even fails).

The same is true for `execute_command_` commands.

Is there a method for accomplishing the expected behavior? I haven't found it documented.

Related:
https://github.com/ahrm/sioyek/issues/127#issue-1128774932

**Comment by ahrm** [comment]
Added the ability to escape spaces with backslash in 8102dc41352694c8250d2f84798c1aca0bc35d6f. Note that we don't run custom commands as shell commands but we use Qt's subprocess mechanism. The exact method used to be something like this:
* split the command using spaces
* treat the first part as the executable and the rest as arguments

This means somethings like piping would not work. For example executing this:
```
echo test > file.txt
```
would just run the echo command with parameters `['test', '>', 'file.txt']`.
Implementing a full command line parser which allows things like this is outside the scope of sioyek. For now if you want to execute complex commands I recommend putting the commands in a script file and running the script from sioyek.

Also note that in newer commit of sioyek we use a better mechanism for custom commands. Instead of using `execute_command_*`, you can define a named command like this:
```
new_command _embed_annotations python -m sioyek.embed_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}"
```
Note that custom command names must begin with a '_'. Now you can bind `_embed_annotations` to a keybind the same way to you would bind a build-in sioyek command in your `keys_user.config`:
```
_embed_annotations <keybind>
```

Also custom commands appear in sioyek's command menu.

**Comment by mreppen** [comment]
Thanks!

I have a bunch of short one-liners that work fine to execute with `bash -c "..."`. That should now work with backslash escaping spaces! (even if not the most ergonomic :))

I will try it out once I have ticked off some deadlines, but will close this for now.

PS. It might be useful to add another `%` expansion for PID at some point.

**Comment by mreppen** [comment]
Confirmed to work as expected
