### ISSUE TITLE
[Feature request]Regular expression search

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#407]
Using a regular expression literal, which consists of a pattern enclosed between slashes, as follows:
`/[a-z]{3}/`

**Comment by ahrm** [comment]
Added a `regex_search` command in d0af36c158df10a8f0e8def704a4fee504dc3a17. Note that this functionality is disabled by default (because it increases memory usage a little bit). You need to enable it by adding the following to your `prefs_user.config` (requires a document reload to take effect):
```
super_fast_search 1
```

In addition to enabling regular expressions, this also considerably increases normal search speed. For example here we find all 73531 instances of lower case or upper case 'a' in a 730-page document almost instantly.

https://user-images.githubusercontent.com/6392321/188644429-0b91e41d-f08f-487f-b865-9574ec75493e.mp4

**Comment by wenbopeng** [comment]
> Added a `regex_search` command in [d0af36c](https://github.com/ahrm/sioyek/commit/d0af36c158df10a8f0e8def704a4fee504dc3a17). Note that this functionality is disabled by default (because it increases memory usage a little bit). You need to enable it by adding the following to your `prefs_user.config` (requires a document reload to take effect):
> 
> ```
> super_fast_search 1
> ```
> 
> In addition to enabling regular expressions, this also considerably increases normal search speed. For example here we find all 73531 instances of lower case or upper case 'a' in a 730-page document almost instantly.
> 
> 1.00
>  2022-09-06.17-39-07.mp4

awesome！

**Comment by amzon-ex** [comment]
Hi. Is this function not there in the stable release yet?

**Comment by ahrm** [comment]
No.
