### ISSUE TITLE
Using small pop-up window/notification to quickly show the references  

### ISSUE THREAD

**Issue by A3EKV** [ahrm/sioyek#43]
Hello,
A cool feature that I find very useful in many websites such as ScienceDirect, Wikipedia(when using the wikiwand extension*****), etc. is that when you click on a reference number instead of jumping to the reference in the References section, it show a little pop-up notification showing the full reference.

IMHO, this is way better than using bookmarks, or portals.

*****Here is a screenshot from wikiwand, when I click on reference number 2, it will show the reference instead of jumping:

![image](https://user-images.githubusercontent.com/90999345/133916280-0993fdec-668c-41e2-92ca-f11149b21724.png)

**Comment by ahrm** [comment]
Personally I am not a huge fan of this feature in websites like wikipedia/etc. . But it seems like a lot of people enjoy this feature so I may add it as an optional feature if it doesn't prove to be too hard to implement.

**Comment by ahrm** [comment]
I have added a simple implementation of this feature in 486bc50cc891fd93a6ecb5be0bb8d729c1110e73. It just shows the target link in a popup in the middle of the screen. It is off by default, in order to enable it you have to add this to your config file:
```
hover_overview     1
```
Of course it doesn't always work perfectly because there is a lot of variation in how PDF documents handle their links, for example some documents just link to the top of the target page and don't specify the exact location of the link within the page. Of course for such documents, this feature doesn't work perfectly.


https://user-images.githubusercontent.com/6392321/133930465-a1cd29e7-6667-4f7d-801c-bdd19b5f33b0.mp4

**Comment by fanmih** [comment]
Even from this first implementation it looks great!

**Comment by A3EKV** [comment]
@ahrm : Thank you very much for implementing such a nice feature <3
