### ISSUE TITLE
Overview does not work with some pdf

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#441]
Just found a pdf where overview often does not work :

When right-clicking on **Example 3-31** or **Example 3-30** (see picture below), no overview appears (just the visual mark).

![0overview](https://user-images.githubusercontent.com/52013479/193410852-709fdfd7-e581-4878-a92f-df1c0c7da8ad.png)

Please find attached the said pdf page, if you want to test with Sioyek :

[sample.pdf](https://github.com/ahrm/sioyek/files/9690446/sample.pdf)

**Comment by ahrm** [comment]
This is a scanned document (there is no text, this is just an image).

**Comment by Elaws** [comment]
@ahrm : My bad, please find here the correct pdf sample :

[sample.pdf](https://github.com/ahrm/sioyek/files/9690448/sample.pdf)

**Comment by ahrm** [comment]
There are two reasons why this document doesn't work. One is the use of `-` instead of `.` as the separator. This can easily be fixed.
However, the deeper reason why this doesn't work is that we assume the destination tags always start with an upper-case letter, while the `EXAMPLE 3-31` in this document appears to be upper-case, if you copy the text you will see that it is `example 3-1` which doesn't work with our heuristic.

So I would say this is an issue of improper document (the displayed text doesn't match with the actual text). I won't fix it, because fixing it increases the false positive rate of properly formatted documents.

**Comment by Elaws** [comment]
Mmm, this makes sense, which is unfortunate ! I can't think yet of another way to make this work.

A workaround is simply to use portals, in case of documents that do not match the heuristic of Sioyek.

**Comment by ahrm** [comment]
> A workaround is simply to use portals, in case of documents that do not match the heuristic of Sioyek.

Yes, I have also recently added `overview_to_portal` command which helps with this.
