### ISSUE TITLE
[feature] Pdf name in status bar

### ISSUE THREAD

**Issue by jmburgos** [ahrm/sioyek#443]
Hello,

Would it be possible to have an option to include the name of the pdf in the status bar (i.e. where the page number and section are shown), instead of the title bar?  I use a tiled window manager which does not show the title bars of the applications.  When I have several pdfs opened, it is hard to know which window is visiting each pdf.

Thank you for an excellent sofware!

Julian

**Comment by ahrm** [comment]
This is an easy option to add, however I can't add it now because [my piece of shit government is blocking my internet](https://slate.com/technology/2022/09/iran-protests-mahsa-amini-internet-censorship.html). I can view github but I can't push anything. You'll have to wait until my internet returns to normal.

**Comment by jmburgos** [comment]
Of course.  We are following the news and the entire situation sucks.  I hope things will get better soon.

**Comment by ahrm** [comment]
Added a `show_document_name_in_statusbar` option in 58cc04c9b1d618276fcbae194cf3910adf7d6df8.

**Comment by jmburgos** [comment]
Works great! Thanks!
