### ISSUE TITLE
Annotations 

### ISSUE THREAD

**Issue by IsaacDLS** [ahrm/sioyek#46]
It would be nice if it has annotations like Adobe Reader/Okular.

**Comment by ahrm** [comment]
What kind of annotations do you mean? We have bookmarks which are kind of like text comments and we have highlights.
Also if you mean annotations that modify the PDF itself and are visible in other PDF viewing software, we probably will never have those because of the reasons explained here: https://github.com/ahrm/sioyek/issues/38#issuecomment-916107614 .

**Comment by A3EKV** [comment]
> What kind of annotations do you mean? We have bookmarks which are kind of like text comments and we have highlights.
> Also if you mean annotations that modify the PDF itself and are visible in other PDF viewing software, we probably will never have those because of the reasons explained here: [#38 (comment)](https://github.com/ahrm/sioyek/issues/38#issuecomment-916107614) .

Maybe in the future one can create an external tool/plugin  that will merge the highlights and the PDF file to generate another PDF with highlights/annotations included.

**Comment by IsaacDLS** [comment]
> What kind of annotations do you mean? We have bookmarks which are kind of like text comments and we have highlights.

Inserting lines, shapes, and signatures

> Also if you mean annotations that modify the PDF itself and are visible in other PDF viewing software, we probably will never have those because of the reasons explained here: https://github.com/ahrm/sioyek/issues/38#issuecomment-916107614 .

Noted on this. Maybe having an option to print it on pdf would be a good workaround if someone wants to "flatten" the annotations on the pdf. 



Anyways, thanks for the response.

**Comment by Creling** [comment]
>  We have bookmarks which are kind of like text comments.

what about showing bookmark content near the bookmark anchor? 
Currently, I can hardly be aware that I used to make a bookmark here if I review the paper several days later.

**Comment by runtimeee** [comment]
> What kind of annotations do you mean? We have bookmarks which are kind of like text comments and we have highlights. Also if you mean annotations that modify the PDF itself and are visible in other PDF viewing software, we probably will never have those because of the reasons explained here: [#38 (comment)](https://github.com/ahrm/sioyek/issues/38#issuecomment-916107614) .

can sioyek put the config data in the same directory with the PDF files? or replace the absolute file path with relative one when exporting configs ?

**Comment by ahrm** [comment]
> > What kind of annotations do you mean? We have bookmarks which are kind of like text comments and we have highlights. Also if you mean annotations that modify the PDF itself and are visible in other PDF viewing software, we probably will never have those because of the reasons explained here: [#38 (comment)](https://github.com/ahrm/sioyek/issues/38#issuecomment-916107614) .
> 
> can sioyek put the config data in the same directory with the PDF files? or replace the absolute file path with relative one when exporting configs ?

No, what does it even mean for config data be in the same directory as the PDF files? PDF files might be in different locations.

**Comment by DOFfactory** [comment]
well, the macOS app Skim created next to every `.pdf` file a corresponding `.skim` file with the annotations included. I wonder whether this could be implemented with sioyek, as currently the cooperation between `shared.db` files and `embed_annotation` command is not very functional across Win/Linux :-(

**Comment by linwaytin** [comment]
This is a nice pdf viewer, with a lot of useful functionalities for researchers. 

However, I would say without a convenient way to store annotations inside the pdfs, I cannot adopt this viewer. This design is exclusive. If you use this viewer to annotate a pdf, you cannot use another pdf viewer to read the same pdf, because the annotations are not along with the file. I cannot see the much benefit of this decision. 

Anyway, I still think this is a great project.

**Comment by ahrm** [comment]
For the record, it is possible to embed all annotations in the PDF file using the `embed_annotations` command. However, keeping the annotations in a separate database files has many advantages and is key to the design of sioyek, so it is unlikely that we ever change that, here are some of the advantages:
* Can be used when you don't have write permission on the PDF files
* All your data can easily be synchronized by just sharing one database file
* You can globally search all annotations on all files very quickly

**Comment by DOFfactory** [comment]
Well, allow me to comment on these points. As researchers, we often use multiple computers with various shared accounts (Dropbox, OneDrive, Sharepoint, etc). Even if one tries to use a `shared.db`, the paths would be different for every client, so this is causing a bit of difficulty to set up for every single individual client and maintain it consistently. I tried to set up Windows 10 and Fedora, in the latter finding the correct path was quite a journey. 

Often on multiple machines we are forced to use shared reference manager files as well (bibtex). The reference manager file takes care of the keywords, comments, but also can search in full-text. So no need for a 3rd point in most of the cases. However, what is really really p*ssing me off is that I cannot embed annotations into the same file I am reading, it needs to be saved into a different one. This breaks the link with the reference file... however good is sioyek, until this behaviour pertains it is 100% unusable for me and most of us with organized reference management. 

This also makes it impossible to import already annotated PDFs, as the shared.db does not see the annotations. Migration to sioyek then is a problem.

We researchers often need to share our datasets (open science), share our annotations for literature reviews across multiple teams. Sharing highlights easily is absolutely crucial for 21st century science. Thus, the annotations should not migrate in a database, but rather with the PDFs.

Back to your 1st point: I mean seriously, who does not have access to their PDFs? Why would you comment on a PDF to which you do not have write access to? Then make a copy first and then annotate.

**Comment by ahrm** [comment]
> Even if one tries to use a shared.db, the paths would be different for every client

Well, that is another advantage of not modifying PDF files! Because we don't change the files, we can use the hash of the file as a unique identifier. So it doesn't matter if the paths are different, it should still work (you just need to open the file once using sioyek so that it knows it exists).

> Back to your 1st point: I mean seriously, who does not have access to their PDFs? Why would you comment on a PDF to which you do not have write access to? Then make a copy first and then annotate.

Here is a comment from when I shared sioyek for the first time on hackernews about a year ago (and this was before we has any annotations):

> Annotations are super useful.
Please consider storing the annotations external to the PDF. For example, Okular wants to save these to the PDF itself. This doesn't work very well with a read-only network drive (read: corporate environment).

Anyway, I am not dismissing your issues (that is why we have the `embed_annotations` command), however at this point it is too late to change the way that we are storing annotations even if I wanted to.

**Comment by ahrm** [comment]
Like I said, it is pretty important for sioyek not to modify PDF files so I won't add this to the main sioyek source code. However, what you want can be achieved using the [external script system](https://ahrm.github.io/jekyll/update/2022/07/05/implementing-a-screen-reader-for-sioyek.html).
I made a simple script that does what you want here: https://github.com/ahrm/sioyek/blob/main/scripts/embedded_annotations.py

Here is how it looks like:

https://user-images.githubusercontent.com/6392321/180283893-85b94515-aeb3-42fa-9279-e7054f282c1a.mp4

**Comment by linwaytin** [comment]
This looks great! I will try it once I have time. Thanks for implementing this feature.

**Comment by Aneeqasif** [comment]
yes above script looks awsome , ill try that , more over i totally repsect author's design choice on not changing the pdf itself but for different use cases it can be petty annoying that highlights needs to be syced in order to see them on other devices and other users like even in a small team of people that are collaborating on some project it can be challenge to sync and secondly this forces that all other people should also have to be using this pdf reader in order to have this functionality + they should sync database , and syncing database by itself doesn't make sence in a collaborative environment like if all people are mainlining their own database how this thing will work if they are  sharing pdfs and how the database gonna merge without disturbing that person's personal data base. i am leading a research group at my uni and may time while reviewing research papers on zoom we highlight import stuff with different colors  and then share it after the meeting , given that design choice it really leaves me no option to switching back to okular pdf reader. if there is a option to be enable/disable like weather **I want** to embed those highlights in my pdf or not , i**f the user were given the choice** i never ever had left this software for sure .
given this design choice it seems that this software is intended to be only used by one single user who does not collaborate wth any one and will never need to do so.
this issue might be old but i avoided creating a new one cz if authors have already decided to dump such kinda use cases then why should i bother them , they might be working something useful. so this comment can lie here for ages like several other issues , comments, and PRs

**Comment by x61** [comment]
> Like I said, it is pretty important for sioyek not to modify PDF files so I won't add this to the main sioyek source code. However, what you want can be achieved using the [external script system](https://ahrm.github.io/jekyll/update/2022/07/05/implementing-a-screen-reader-for-sioyek.html). I made a simple script that does what you want here: https://github.com/ahrm/sioyek/blob/main/scripts/embedded_annotations.py
> 
> Here is how it looks like:

Is this in version 2.0 now? I tried the code on mac but it is not working.

**Comment by ahrm** [comment]
Yes, you need to install the python extensions.

**Comment by nickel8448** [comment]
Thanks for writing this. It didn't work on my computer so I changed the script a bit to make it work.

Is there no way to see the annotation in sioyke?

**Comment by ahrm** [comment]
> Is there no way to see the annotation in sioyke?

Not currently.

**Comment by ahrm** [comment]
In the development branch we have added:
* Underline and strikethrough highlights
* Visible bookmarks
* Freetext bookmarks
* Freehand drawings
* Ability to export annotations with a built-in command (no extension required)
* Ability to import PDF annotations with a built-in command

**Comment by linwaytin** [comment]
Looking forward to the new features!

**Comment by Aneeqasif** [comment]
> In the development branch we have added:
> 
>     * Underline and strikethrough highlights
> 
>     * Visible bookmarks
> 
>     * Freetext bookmarks
> 
>     * Freehand drawings
> 
>     * Ability to export annotations with a built-in command (no extension required)
> 
>     * Ability to import PDF annotations with a built-in command

when it will land in stable/main branch?
we all are waiting

**Comment by mithryl** [comment]
The ability to add comments to highlighted text, or a selected region, in a small pop-up window would be very useful (in my case for language learning, being able to highlight a word and include a translation which I can read when I click the highlight). Most of the PDFs I'm working with are poorly scanned and in old scripts. Would this be trivial to add?

**Comment by ahrm** [comment]
This is already added in the development branch.

**Comment by Aneeqasif** [comment]
> This is already added in the development branch.

that's great. can you please suggest what changes in the aur pkgbuild need to be make to get the dev package. i have tried but failed if you can give a aur pkgbuild recipe it will be great at least for arch users for building and testing the software. thanks

**Comment by ahrm** [comment]
I don't recommend publishing a package with the dev build yet. It is still under development and may be incompatible with the final release version.

**Comment by Aneeqasif** [comment]
> I don't recommend publishing a package with the dev build yet. It is still under development and may be incompatible with the final release version.

then how the people who want fixes or new features would get them. at least have a beta package for testing purposes only

**Comment by ahrm** [comment]
I am not on arch so I don't know the exact modifications needed to build the dev branch. The instructions in README do work (I have tested them on windows, linux (ubuntu), and mac) the only difference is that you need qt 6.6 instead of 5.*.

**Comment by mithryl** [comment]
> that's great. can you please suggest what changes in the aur pkgbuild need to be make to get the dev package. i have tried but failed if you can give a aur pkgbuild recipe it will be great at least for arch users for building and testing the software. thanks

The current sioyek-git package in the AUR is using the development branch and compiles fine. 

> This is already added in the development branch.

Awesome, that's exactly what I was looking for. One issue, though: I see that I can add comments to highlights now, but there is text that I can't highlight due to the PDF being a scan. The text isn't selectable. I'd like to be able to do a rectangular selection which has this same functionality as a normal highlight—namely, being able to add a comment to the highlighted area/box and then view that comment when I click on it. Is this functionality added?

**Comment by ahrm** [comment]
> The current sioyek-git package in the AUR is using the development branch and compiles fine.

Oh boy. I would like to warn people that when the next version of sioyek is released, in likely will be incompatible with the data saved in the development branch. Now it probably will be possible to move the data by slightly modifying and renaming the database files, but I just want people to know what they are getting into.

>Awesome, that's exactly what I was looking for. One issue, though: I see that I can add comments to highlights now, but there is text that I can't highlight due to the PDF being a scan. The text isn't selectable. I'd like to be able to do a rectangular selection which has this same functionality as a normal highlight—namely, being able to add a comment to the highlighted area/box and then view that comment when I click on it. Is this functionality added?

Yes, using `add_marked_bookmark` and `add_freetext_bookmark` commands.

**Comment by Aneeqasif** [comment]
> Oh boy. I would like to warn people that when the next version of sioyek is released, it likely will be incompatible with the data saved in the development branch. Now it probably will be possible to move the data by slightly modifying and renaming the database files, but I just want people to know what they are getting into.

yes sir. don't worry , people installing this dev package are going to be most bet testers who want to try new features. one thing i would suggest will be to get this package renamed to sioyek-beta instead of sioyek-git.

**Comment by Qkessler** [comment]
Specially interested in this one:
> * Ability to export annotations with a built-in command (no extension required)

Any updates on stabilization? What is needed to drive this to completion? Happy to help!

**Comment by ahrm** [comment]
This is already implemented in the development branch.

**Comment by levihuayuzhang** [comment]
> This is already implemented in the development branch.

Wondering how to use underline annotation? (The key shortcut?) Searching for a while in the doc but cannot find it. (I guess i'm already in the `development` branch and was built from source for M1 Mac with HEAD of the tree).

**Comment by ahrm** [comment]
Uppercase letter symbols are rendered as underline.

**Comment by levihuayuzhang** [comment]
> Uppercase letter symbols are rendered as underline.

Thanks, that's an amazing one.

**Comment by affans** [comment]
Could I ask what the development state is at this point and how close you are to tagging a new version with annotations?

**Comment by ahrm** [comment]
There is a preview release here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0.
