### ISSUE TITLE
importing bookmarks, wrong offset_x and not able to delete highlight

### ISSUE THREAD

**Issue by blob42** [ahrm/sioyek#482]
Hi, thanks for this project. 

I am trying to import bookmarks from Koreader using their Json export and Sioyek python library. 

My input data looks like this:
```
    "entries": [
        {
            "page": 3,
            "sort": "highlight",
            "drawer": "lighten",
            "text": "Bodner gets Go. In clear, lively prose, he teaches the language from its basics to advanced topics like reflection and C interop. He demonstrates through numerous examples how to write idiomatic Go, with its emphasis on clarity and simplicity. He also takes the time to explain the underlying concepts that can affect your program’s behavior, like the effects of",
            "time": 1665232736,
            "chapter": "Cover"
        }
    ],
```

on my python script I load the file based on its md5 hash then I do: 
```py
In [43]: doc.get_best_selection(2, hi['text'])
Out[43]:
((76.80986785888672, 407.3799743652344),
 (431.9998474121094, 456.8699951171875))
```
But this is the wrong highlight zone, when I do the highlight directly on a sioyek instance like this:
```py
doc.highlight_page_text(hi['page'] -1, hi['text'])
sioyek.add_highlight('k')
```
I get a different highlight offset_x 
```py
In [24]: hl.get_begin_document_pos()                             Wed 21:12
Out[24]: DocumentPos(page=2, offset_x=-175.563, offset_y=406.9559999999997)

In [25]: hl.get_end_document_pos()
Out[25]: DocumentPos(page=2, offset_x=179.824, offset_y=456.8159999999998)
```

# Sticky highlights when inserted with sqlite

On a separate issue related to the import. I am trying to insert the highlights using an sqlite query, when I open the file on sioyek I see the highlight (with the wrong zone as noted above) but if I delete the highlight and quit sioyek with `:q` I find back the highlight when I relaunch. If I do highlights manually on sioyek I can delete them without problem.

It looks like the highlights I insert with sqlite queries cannot be deleted from sioyek. See below in example of the query from Python and the corresponding inserted row

```py
    INSERT INTO highlights (document_path,desc,type,begin_x,begin_y,end_x,end_y)
    VALUES ('{}','{}','{}',{},{},{},{});
    """.format(hash, hi['text'], "k", hi['begin'].offset_x, hi['begin'].offset_y, hi['end'].offset_x, hi['end'].offset_y)
```
-> inserted row:
```

225 | 4ed58fe4dd7d8801f392f901eb48947b | Bodner gets ... | k | 76.8098678588867 | 1730.28397436523 | 431.999847412109 | 1779.77399511719
```

**Comment by ahrm** [comment]
About the first point:
Sioyek uses a different coordinate system than mupdf for document coordinates. In sioyek's system the `offset_x` of the middle of the page is zero, so you have to add half of the page width to convert it to mupdf coordinates.

About the second point, I am not able to reproduce the issue. Here are the steps I take:

* create a sioyek instance in python
* select the target text in sioyek app
* run `sioyek.add_highlight('k')`
* delete the highlight in sioyek app
* the highlight remains deleted when sioyek is restarted

One detail about sioyek which may be relevant to your case is that we cache the hash of the file after the first time it is computed. This has the advantage of reduced loading time when file is subsequently opened and also allows for example highlighting/bookmarking changing latex documents. But it does mean that the cached hash doesn't always correspond to the actual hash of the file. So if you are computing the md5 hash of the file yourself, it might be different from the one that sioyek uses (you can find that one in `local.db` file). Though I doubt this is your issue because if that was the case you shouldn't even be able to see the bookmark in sioyek.

**Comment by blob42** [comment]
> Sioyek uses a different coordinate system than mupdf for document coordinates. In sioyek's system the `offset_x` of the middle of the page is zero, so you have to add half of the page width to convert it to mupdf coordinates.

Thanks I will try this I think that's the issue. 

Would it be possible to move the coordinates calculations for highlights within sioyek rendering logic so that the shared db only contains text and page numbers ? That would allow easy import of highlights from any other export. Or would it be too expensive performance wise ?

> About the second point, I am not able to reproduce the issue. Here are the steps I take

The steps to reproduce this issue would be to manually insert the highlights in the shared db with an sqlite statement. basically like the following steps:
* create instance
* I only use sioyek instance to obtain highlight coordinates
* create connection to shared db
* manually insert in the highlights table
* Open the document on live sioyek instance
* Delete the highlight and close sioyek
* Restart the app, the highlight will appear again

> One detail about sioyek which may be relevant to your case is that we cache the hash of the file after the first time it is computed

I only use PDF documents and do not embed anything in them, should I worry about changing hashes ? 
Also what would be a better approach to find the document path ?

**Comment by ahrm** [comment]
> Would it be possible to move the coordinates calculations for highlights within sioyek rendering logic so that the shared db only contains text and page numbers ?

That's not a valid solution because a page might contain multiple copies of the same text.

> The steps to reproduce this issue would be to manually insert the highlights in the shared db with an sqlite statement. basically like the following steps:

Well that should not be different because internally sioyek performs the same databse insertions. You can use a sqlite browser like this: https://sqlitebrowser.org/ to view the file after inserting a highlight in sioyek vs inserting a highlight manually and see if there is a difference.

> I only use PDF documents and do not embed anything in them, should I worry about changing hashes ?

No.

> Also what would be a better approach to find the document path ?

There is a table in `local.db` which maps document paths to hashes.

**Comment by blob42** [comment]
I am already using local.db to recover the file path. here's the code I'm using to do it: 
```py
book_title = ko_export.get('title')
book_hash = ko_export.get('md5sum')
path_hashes = sioyek.get_path_hash_map()
hash_paths = {value: key for key, value in path_hashes.items()}
local_book_path = hash_paths[book_hash]
 doc = sioyek.get_document(local_book_path)
``` 

I am also using sqlite browser to verify and my query is similar to the one inserted by sioyek native highlight. The ones I insert with my script cannot be deleted, I have to delete manually the row from the highlights table in the shared db for them to disappear from the PDF when I reopen it on sioyel. 

Let me explain my use case. I have highlights on KoReader with the same PDF books on both my ebook reader and my laptop where I use sioyek. I was thinking I can use the md5 sum of the pdf file to match its local path on my laptop and then do the import of the highlights.

**Comment by blob42** [comment]
I fixed the issue with the offest_x, I had to substract (not add) half the width of the page, maybe it would be work mentioning in the Coordinate Space section of the docs. 

So now my highlights are perfectly being added from my import script  which I [am sharing here if you want to take a look](https://github.com/blob42/sioyek-import-highlights/blob/main/import_koreader_highlights.py). 

However no matter what I do it is impossible to delete those manually added highlights from sioyek, as soon as it's restarted they reappear. 

Here a capture of the last inserts in the highlights table. 

![2022-11-03-110508_1929x346_scrot](https://user-images.githubusercontent.com/210457/199693830-e85b6249-cbb0-44bd-82a4-f8eb879b82b0.png)

**Comment by ahrm** [comment]
I am still not able to reproduce your issue. Here is the exact script I used to try to reproduce, maybe you are doing something different? :

```py
from sioyek import sioyek

path = '/path/to/sioyek/folder/'
app = sioyek.Sioyek(path + 'sioyek.exe', path + 'local.db', path + 'shared.db')
path_hash = app.get_path_hash_map()

pdf_file_path = '/path/to/pdf/file.pdf'
pdf_file_hash = path_hash[pdf_file_path]

shared_database = app.get_shared_database()

doc = app.get_document(pdf_file_path)

print(doc.get_highlights())

begin_x = -66.31
begin_y = 239.5
end_x = -11.15
end_y = 294.6

query = """INSERT INTO highlights (document_path,desc,type,begin_x,begin_y,end_x,end_y)
    VALUES ('{}','{}','{}',{},{},{},{});
    """.format(pdf_file_hash, 'this is a test', "k", begin_x, begin_y, end_x, end_y)


cursor = shared_database.cursor()
cursor.execute(query)
cursor.execute('commit')
cursor.close()

print(doc.get_highlights())

shared_database.close()
```

The highlights created using this script are perfectly capable of being deleted by sioyek.

If you are still encountering this issue, maybe try to create a minimal `local.db` and `shared.db` file that has this issue and share it with me (along with the PDF file) so that I can test it on that file. (In order to create new database files you can first backup your previous database files and then delete them, sioyek will create empty new ones if it can't find the previous database files).

**Comment by blob42** [comment]
Thanks for the sample code taking time to answer. I think it might be related to the precision of the highlight positions. 

When I highlight through sioyek app for the same text/page I get  `begin=(-173.46 , 1734.96)  end= (183.12 ,1772.34)`

In my script I use `doc.get_text_selection_begin_end()` which returns (after convert to abs) `begin=(-175.19, 1730.28)  end= (179.99 ,1779.77)` which is slightly different than the GUI app. The highlight shows perfectly though, only it's undeletable, so no possible to modify it. 

I [uploaded here](https://github.com/blob42/sioyek-import-highlights) a new minimal shared and local db and used a totally different pdf and highlighted text that produces the same effect. The repo includes all the files needed to reproduce it. 
 
Also I am using the build from the latest commit.

**Comment by ahrm** [comment]
I was able to reproduce the problem. It should be fixed in 92ddb111772c3a23723a0ac8cfdcf6d54d7cf1e0.

**Comment by blob42** [comment]
Thank you very much for the fix it works perfectly now :)

**Comment by blob42** [comment]
FYI [here's the link](https://github.com/blob42/koreader-sioyek-import) to a somehow clean script I used it to import all my highlights from koreader. In case you want to add it as an example.

**Comment by ahrm** [comment]
Thanks, added to the readme page of sioyek extensions repo.
