### ISSUE TITLE
[ BUG ] toggle_highlight stops working randomly + [ Suggestion ]

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#497]
I've added it to my startup commands, but the highlights randomly disappear. When I press `f` to `open_link`, the highlights show up, but they disappear again after pressing `esc`.

ALSO, it'd be nice to highlight smart links as well. For example, instead of ctrl-clicking on references, we should be able to just use the keyboard: press `f` to see the (smart) link and then press the shortcut to go there (like Vimium on Chrome/Firefox or Zathura).

**Comment by ahrm** [comment]
Added a `highlight_links` config option in 417074d87d8021f4001b92fc2580cab1a474f400.

> it'd be nice to highlight smart links as well

This is impossible, since there are many false positives when detecting link locations. We rely on the user clicking on a text to be a proof that this location is a link source. Note that we have the following commands which allow you to simulate clicking using keyboard:

* `keyboard_select`
* `keyboard_smart_jump`
* `keyboard_overview`
