### ISSUE TITLE
[Feature request] Mouse drag mode while holding key

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#517]
Currently, it is possible to toggle mouse drag mode by binding `toggle_mouse_drag_mode` to a key. That is, you press a key to activate/deactivate mouse drag mode. It would be more useful to activate mouse drag mode while holding a key. For instance, mouse drag mode is activated while holding the space key. This is how Figma implements its pan mode, and to me, it feels more natural than pressing a key to activate/deactivate it. This could be implemented by activating the mouse drag mode on the key-down event and deactivating it on the key-up event.

**Comment by ahrm** [comment]
Sioyek's input system does not distinguish key-up and key-down events so it is impossible to implement using the current input system. It could be added as a special case but I don't think this is important enough to warrant complicating the input handling code.

Of course, this functionality could be added using external programs, for example, on windows you could program autohotkey to send two events for key-down and key-up for a specific button when sioyek is opened. I am sure there are equivalent programs for other operating systems.

**Comment by tgharib** [comment]
For anyone looking for a stateless solution because they found the drag mode frustrating since it takes up mental bandwidth, I recommend either using the scroll wheel on your mouse or binding `move_down` and `move_up` in sioyek config to keyboard keys:

```
move_down <space>
move_up <S-<space>>
```

**Comment by gokberkgunes** [comment]
After using zathura for a long time, inability to pan using the middle mouse button is the hardest change to adapt. Therefore, I am in search of some alternative ways to solve the issue.

Most of the time there is a need of zooming into some detail, e.g. pictures, with the mouse wheel. Then, the  zooming in typically requires user to pan around and check details. Even though it is possible to do this operation after switching to `drag mode`, the need of pressing the keybinding before and after panning is very taxing.

It appears to be zooming with keyboard and then panning with `hjkl` seems like the only alternative I could've found. Is there any other way to this problem? Can't we just change `drag_mode` to `normal_mode` and let the middle mouse button to pan instead of left mouse button?

@ahrm, can you please comment on the above suggestion, do you think it is reasonable? It seems like there is no need to complicate the input handling code too.

**Comment by ahrm** [comment]
We already use middle mouse button for smartjumps, but maybe we could use it only when the mouse has not moved too much and otherwise use it to pan the document.

**Comment by HakonHarnes** [comment]
> We already use middle mouse button for smartjumps, but maybe we could use it only when the mouse has not moved too much and otherwise use it to pan the document.

Perhaps we could do left double click for smart jumps and middle button for panning? That would at least make more sense to me. 

This doesn't have to be the default behaviour of course, but it would be useful to be able to configure Sioyek to behave this way at least.

**Comment by ahrm** [comment]
Added the ability to use middle mouse button to pan the document in the development branch. If we just click using the middle mouse button we use the old functionality (smart jump, etc.) but if we start moving the mouse while holding middle mouse button we start panning instead.

**Comment by 777uliahshafar** [comment]
This a good feature, I hope this realease soon with much more consideration with smart jump and this feature.
