### ISSUE TITLE
color of figures in custom color mode

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#571]
The dark mode doesn't seem to affect the colour of figures in the PDF (only background and the text)) but when I'm in custom color mode it seems that all my figures get faded or affected by the background colour. Is there a way to disable (or configure) this behaviour?

**Comment by ahrm** [comment]
No.

**Comment by mil-ad** [comment]
I think it might be some sort of alpha value that gets applied in custom mode but doesn't exist in dark mode?

**Comment by mil-ad** [comment]
Example:

default:

![image](https://user-images.githubusercontent.com/686449/209690461-07a3eb07-7029-4062-9a30-d347c65f4d78.png)

Dark mode:
![image](https://user-images.githubusercontent.com/686449/209690538-065b2f69-1e93-42dc-bd42-2d3ecc26beab.png)

My custom mode:
![image](https://user-images.githubusercontent.com/686449/209690600-b79ba45b-6cba-4086-9dfa-cd8b54fe13c2.png)

I think (?) the benefit of the custom mode is that I can configure the text color, which is really nice, but I wished I could get the same figure colors as in dark/white mode.

**Comment by ahrm** [comment]
I understand, however, like I said, it is not possible to do without detecting the figures. We can't do something like just mapping the black color to text color and white color to background color (because not all texts are black and not all backgrounds are white, also because of antialiasing it would look terrible because even when the texts are completely black, their borders are not).

Maybe we could find some way to better keep the hue of the color, I am not sure how though.

**Comment by mil-ad** [comment]
ah, I think I get it. So this happens because custom mode allows changing text color right?

**Comment by ahrm** [comment]
Okay, I was wrong. It is possible to improve the contrast even without detecting the figures. We use a new algorithm in 60de8c1aca24e8b1a30986c3905c3877a52768e2 which should improve the results. Here is a comparison:

![new_custom_color](https://user-images.githubusercontent.com/6392321/209947351-0c495418-1fc4-455b-9466-ddd804a867a2.png)
![old_custom_color](https://user-images.githubusercontent.com/6392321/209947357-4f8afc89-b766-4044-9cff-5e0622a5d564.png)

**Comment by mil-ad** [comment]
This worked perfectly!! Thank you!
