### ISSUE TITLE
UI issues, especially with touch and inking

### ISSUE THREAD

**Issue by Jaifroid** [ahrm/sioyek#588]
As a potential user dropping in to try out Sioyek, I love the speed and the focus, but I think usability is a bit of an issue despite the tutorial displayed on first launch.

First off, it really needs a menu that is on by default, and that can be turned off when the user has learnt the keyboard commands. The keyboard commands are not intuitive on their own. I get that, once learnt, it offers a very fast way of interacting with the document.

Second, intuitive touch gestures (with touchscreen) that would be expected nowadays of any application are not supported. When I open a document, the first thing I want to do is scroll down with touch, but doing so selects text instead. Likewise if I pinch in or out to zoom, it just selects text. If I don't have the physical keyboard connected to my touchscreen tablet (Windows), the application is virtually unusable.

Finally, pen input also only selects text. When picking up a pen and writing on the screen I would expect inking to be engaged, or at least pen options to show. For example, I mostly want to read and annotate PDFs with a pen, or mark students' work (add ticks, underline things), and this doesn't work at least without finding a keyboard command (?).

I realize this may not be your use case for this application. But adding these things, if possible, would make the application much more user-friendly. Please don't take this as criticism, but in the spirit of constructive feedback.

**Comment by ahrm** [comment]
Thank you for the feedback.

> First off, it really needs a menu that is on by default

I highly disagree. I do have some strong opinions about this (and I admit they are not conventional), but I genuinely think all toolbars should be removed from all software. The reason is that toolbars usually impair the experience of advanced users only to make it easier for inexperienced users. Now here is the thing: for most software, 99% of the time spent in the software is by experienced users. So you are making 99% of the time spent in your software worse just for the 1% inexperienced users.

Now you might argue that if toolbars are optional, an experienced user can turn them off. However, even optional toolbars send the wrong message that it is okay to use them (otherwise why would the developer put it there). So it deters the users from actually learning how to efficiently use the software.

Here is an example: I frequently use Audacity to record audio. Despite using it for many years, I always click on the giant red record button to start recording instead of using a shortcut. Why? Because why would the developers put a giant red recording button in the toolbar if I was supposed to use a shortcut?

> about touch gestures and pen support

I agree that touch and pen support is lacking. Note that I developed sioyek to make my own research life easier, and I don't have a touch tablet or a pen, so I am not really motivated to develop this (nor can I easily test it if I wanted to develop it). 

We do have a `toggle_mouse_drag_mode` command which uses touch to move the document instead of selecting text, but it is far from a polished touch experience.

**Comment by ahrm** [comment]
We have added extensive touch and pen support in the development branch (you can enter touch mode using `toggle_touch_mode` command).
