### ISSUE TITLE
Inverse search synctex not working on mac.

### ISSUE THREAD

**Issue by ahmdedshakil** [ahrm/sioyek#675]
I added the specified line in the documentation to the prefs.config file as follows:
`inverse_search_command "/Applications/Visual Studio Code.app" "/Applications/Visual Studio Code.app/Contents/Resources/app/out/cli.js" --ms-enable-electron-run-as-node -r -g "%1:%2"`
However the inverse search isn't working, instead of the error that would happen before adding the line nothing happens now.

**Comment by hajg-ijk** [comment]
Hello, the following procedure fixed the issue for me. 

You can skip the first part since you already have `code` installed in PATH, but I'm adding it for completeness since I had to do it and other people might have to as well.

First, you need a terminal command for VS Code.
To do this, just open the command palette in VS Code with `cmd + shift + p`, type `Shell`, and select `Shell Command: Install code in PATH` from the list. Once this is done, you will be able to run VS Code from the terminal with the command `code`. 
(This was taken from [here](https://stackoverflow.com/a/36882426), where they also show how to make these changes persist after restarting your computer.)

Second, similarly to what we did for VS Code, you need to be able to run sioyek from the terminal. To do this, should install sioyek through homebrew as suggested on the homepage: in the terminal run `brew install --cask sioyek`.
Alternatively, I believe you can add sioyek to the `PATH` variable manually, but I haven't checked.
In the end, you'll be able to launch sioyek from the terminal by just running `sioyek`.

Now we are all set. 
Change your LaTeXWorkshop settings in the `settings.json` file by adding
```
"latex-workshop.view.pdf.viewer": "external",
"latex-workshop.view.pdf.ref.viewer": "external",
"latex-workshop.view.pdf.external.viewer.command": "sioyek",
"latex-workshop.view.pdf.external.synctex.command": "sioyek",
"latex-workshop.view.pdf.external.synctex.args": [
    "--inverse-search",
    "code -r -g %1:%2",
    // "--reuse-instance",
    "--forward-search-file",
    "%TEX%",
    "--forward-search-line",
    "%LINE%",
    "%PDF%"
  ],
``` 
where the line `"--reuse-instance",` was commented out following this [issue](https://github.com/ahrm/sioyek/issues/768#issuecomment-1640564592).

Lastly, the incriminated line in the `prefs.config` sioyek file should read
`inverse_search_command code -r -g %1:%2`

Don't forget to enable `toggle_synctex` from within sioyek by either running the command or pressing `F4`.

Hope this helps!
