### ISSUE TITLE
(Feature Request) Show document title when browsing files

### ISSUE THREAD

**Issue by ejuarezg** [ahrm/sioyek#711]
Hi @ahrm 

I was wondering if there was an option to show the document title next to the file name when browsing files with Shift-O? If not, is this something that sioyek could potentially incorporate in the future?

Would love to see this feature implemented so that I know which of my files (all named main.pdf) is the right one.😅

Thanks. Keep up the good work.

PS: I apologize if this is already an implemented feature that I missed.

**Comment by ahrm** [comment]
Added in this commit in development branch: https://github.com/ahrm/sioyek/commit/de2bf138bfe5e72f0a0ef1098e63f2ba02f2d6d8. Now we show both file path and automatically detected document name in `open_prev_doc`. Note that the documents should be opened at least once after this update so that their names are stored in database.

**Comment by ejuarezg** [comment]
Thank you! Looking forward to this on the next stable release.
