### ISSUE TITLE
reload on the fly

### ISSUE THREAD

**Issue by aloispichler** [ahrm/sioyek#728]
sioyek updates the view, when the file changes on the disk. But it first cleans the page, and then reloads everything.
When writing LaTeX, for example, it would be desirable to update on the fly, that is, without cleaning the page first. Everything else is distracting, as it often takes long to reload, particularly when working on large documents.
Evince does this nicely, so it would be nice to have even smoother behavior here :-)

Thanks

**Comment by ahrm** [comment]
This should already be the case. See this issue: https://github.com/ahrm/sioyek/issues/165. Which version of sioyek are you using?

**Comment by aloispichler** [comment]
I have started working with sioyek the last month, downloaded from AUR, version 2.0.0.

**Comment by ahrm** [comment]
Maybe your latex extension calls sioyek's `reload` command? (that would cause a flicker because reload command unloads all rendered pages, however, calling reload manually is not necessary because sioyek automatically reloads when the file is changed on disk).

**Comment by aloispichler** [comment]
I just save the .tex-file, latexmk compiles and produces the .pdf. The
extension does not even call sioyek. latexmk usually compiles in 2 or 3
rounds. During this process, the screen blanks each time, and reloads the
pdf every time from scratch.

ahrm ***@***.***> schrieb am Sa., 20. Mai 2023, 15:42:

**Comment by ahrm** [comment]
I would say this is more of a latex bug than sioyek bug. After all how are we supposed to distinguish between a partially rendered or a fully rendered file? (when they both are valid PDF files.). I think the reason this is not a problem is evince is because it doesn't reload the file fast enough.
In the next release of there will be an config to increase the minimum wait time after a file is modified so that latex software is probably done with the file by then.

**Comment by aloispichler** [comment]
Dear ahrm, hello again. This compares evince and sioyek.
Thanks for caring! 

https://github.com/ahrm/sioyek/assets/45781387/e6587883-793f-43c0-b0b3-354a7f1a553c

**Comment by ahrm** [comment]
Should be fixed in this commit in development branch: https://github.com/ahrm/sioyek/commit/eb16f841557d3b372403772ee10301150653d0f1.
