### ISSUE TITLE
[feature request]: Underline, Squiggle & Cros-Out

### ISSUE THREAD

**Issue by icaruszhu** [ahrm/sioyek#751]
First of all, thank you so much for developing Sioyek, which I must say is the most innovative and feature-rich PDF viewer I have come across! It suits my workflow well (though I am an emacs user:-)) 

I have gone through the documentation again, but I cannot find if Sioyek allows users  to put underlines,  squiggles under selected text or cross out something.  Alternatively,  would this be achieved through configuring the preference file with commands such as 
```
add_underline    ==> au
add_squiggle     ==> as
add_cross_out   ==> ac
```
Any advice for achieving the above would be much appreciated. Many thanks indeed!

**Comment by ahrm** [comment]
Current version of sioyek doesn't have these features. Next version will have underline highlights, which is treated the same as normal highlights (e.g. it can be searched in the highlights menu). Any highlight highlighted with a capital letter will automatically be rendered as an underline.

**Comment by InRiPa** [comment]
Really nice to hear! Can we let this issue open until it's implemented. 
I just got my first experience with the software. So far, it seems that highlighting with capital letter just switches the color (using git version). e.g. `hr` turns red and `hR` turns pinkish. 
Also, I didn't find the feature in the documentation.

**Comment by ahrm** [comment]
Yes this is not released yet. I don't recommend making an upper-case highlight in current version of sioyek, it might be a bug :/ .

**Comment by ahrm** [comment]
The source for this feature is released in the development branch of this repo.

**Comment by SuperCowProducts** [comment]
Sadly I have found this to be broken now with my current build (using https://forge.barrettruth.com/barrettruth). I will try and find a January the 21st 2024 commit and see if compiling that works.

**Comment by SuperCowProducts** [comment]
Hmm, can't find anything specific to underline [here](https://github.com/ahrm/sioyek/commits/development/?since=2024-01-10&until=2024-01-22) - @ahrm, do you remember what commit allowed underlining by using the capital letter? It might be possible to easily patch the regression in latest dev once we know that.

**Comment by ahrm** [comment]
I just tested it with the latest commits from the development branch and it still works. Highlighting with a capital letter (e.g. hR) underlines the selected text and highlighting with underline (h_) crosses out the text.

**Comment by SuperCowProducts** [comment]
Sorry for the confusion, I don't know what happened but after `sudo pacman -U sioyek-dev-2.0.0.r1116.g67cfaaef-1-aarch64.pkg.tar.xz` (from https://forge.barrettruth.com/barrettruth/sioyek-dev like https://github.com/ahrm/sioyek/issues/1629#issuecomment-4928004900) it started working again (although I did have to `rm -rf ~/.local/share/sioyek/last_document_path.txt` otherwise the app was refusing to boot). 

I had also tried installing the AUR versions [sioyek-dev](https://aur.archlinux.org/packages/sioyek-dev) and [sioyek-git](https://aur.archlinux.org/packages/sioyek-git) as well as my own version of `sioyek-git` which I modified with `source=("git+https://github.com/ahrm/sioyek.git#commit=656cb35b18a1f1725e5234d3ca8c1185315c22ac")` before this with `git clone https://aur.archlinux.org/sioyek-git.git` and `git clone https://aur.archlinux.org/sioyek-dev.git`, running `makepkg -si` on all 3 (side note: because I am on `arm64`, I of course had to modify the start of each `PKGBUILD` with `arch=('x86_64' 'aarch64')`, but that went fine.

N.B: [sioyek-git](https://aur.archlinux.org/packages/sioyek-git) had a `standard-path-mupdf-build.patch` file, don't know if that somehow carried over to subsequent builds without getting overwritten. This was its contents:

```patch
diff --git a/pdf_viewer_build_config.pro b/pdf_viewer_build_config.pro
index a09b861..0154e5d 100644
--- a/pdf_viewer_build_config.pro
+++ b/pdf_viewer_build_config.pro
@@ -88,7 +88,8 @@ unix:!mac {
     QMAKE_CXXFLAGS += -std=c++17
 
     CONFIG(linux_app_image){
-        LIBS += -ldl -Lmupdf/build/release -lmupdf -lmupdf-third -lmupdf-threads -lharfbuzz -lz
+        DEFINES += LINUX_STANDARD_PATHS
+        LIBS += -ldl -lmupdf -lz
     } else {
         DEFINES += NON_PORTABLE
         DEFINES += LINUX_STANDARD_PATHS
```
