### ISSUE TITLE
Open document embedded from current path in new window

### ISSUE THREAD

**Issue by andreatitolo** [ahrm/sioyek#757]
Hi! first of all, thank you for sioyek, it has become my go-to tool for pdf :)

I wanted to ask, is it possible to "chain" commands in some ways? Example: I have all my pdf stored in the same folder, and I often open more than once at the time, always from that folder. 
Currently, the workflow is: `_new_window -> _open_document_embedded_from_current_path`. It's not a slow process, especially with keyboard shortcuts, but it would be nice to have an option to do it in one command only.

Would it be possible to achieve something like this with either custom commands or scripting?

I read the docs regarding opening files, but if I missed something I apologize in advance! :)

**Comment by ahrm** [comment]
Unfortunately currently there is not clean way to do this. Ideally you should be able to do something like this:

```
new_macro _open_in_new_window open_document_embedded_from_current_path;new_window;prev_state
```

But because of the way that `open_document_embedded_from_current_path` is implemented, it runs immediately and therefore the other parts of the macro are executed before we select the new document and the desired effect is not achieved.

**Comment by andreatitolo** [comment]
I see, thank you for taking the time to answer and explain :)

**Comment by ahrm** [comment]
This is fixed in the development branch.
