### ISSUE TITLE
Sioyek treats the copies as the same file.

### ISSUE THREAD

**Issue by Zewbiee** [ahrm/sioyek#763]
I have a file named `texbook.pdf`, and I make a copy named `answers.pdf`. I hope sioyek treats them as two different files, but it doesn't, and I can't even find `texbook.pdf` and `answers.pdf` simultaneously when I press `shift` + `o`.

**Comment by ahrm** [comment]
We address the files by their content, so it is impossible.

> I hope sioyek treats them as two different files, 

Why? If you explain your use-case there might be another way to achieve this in sioyek.

**Comment by zb-zombie** [comment]
The answers section in `texbook.pdf` is located at the end of the document. I would like to have the answers displayed in the right half of the window. Although portal can achieve this, content in helper window cannot be copied or edited. So naturally, I thought about making a copy and opening it in the new window of sioyek.

And vim also distinguishes different files based on their names rather than their content :)

**Comment by ahrm** [comment]
Why don't you use `new_window` command?

**Comment by zb-zombie** [comment]
> Why don't you use new_window command?

I used, but sioyek cannot remember locations of two windows next time when I open the same file.

> Also you can use edit_portal to jump to the portal location while begin able to copy/etc.

Indeed, but it is usually very annoying to keep alternating between the exercises and the answers. As a result, I prefer to have the exercises in the left half of the window and the answers in the right.

Or is there anyway to make helper window editable?

**Comment by ahrm** [comment]
> I used, but sioyek cannot remember locations of two windows next time when I open the same file.

You can mark the location of the solutions (`mm`) and jump to it quickly when you open the window next time (`m). I realize that this is not ideal but it is a small price to pay in exchange for being able to move files between devices without losing your data.

Alternatively, you can edit the PDF file (for example add a highlight in another PDF viewer which modifies the file) which changes the content and sioyek treats it as a new file (make sure to change the name of the file because sioyek caches hashes so if you use the same file name it might still treat it as the same file).

**Comment by zb-zombie** [comment]
> Alternatively, you can edit the PDF file which changes the content and sioyek treats it as a new file.

I added different highlights in the above two files, and sioyek works well with their own highlights. But still I can't find two files in the `shift open` list simultaneously. And their "last location" is still related.

> Mark the location of the solutions (mm) and jump to it quickly when you open the window next time (`m).

This idea seems good. Thank you!
