### ISSUE TITLE
Change all colors based on dark mode

### ISSUE THREAD

**Issue by 21st-centuryman** [ahrm/sioyek#821]
Hey I just wanted to check if it was possible to change all colors based on dark mode. IE have one set of colors if dark mode is toggled on and another set of colors if its off.
Obviously if you do not state it then the colors will remain the same. 

Is this a feature that exist?

If it does not I could potentially do a port

**Comment by ahrm** [comment]
We do have a custom_color_mode which allows you to specify text and background color (see the documentation here :https://sioyek-documentation.readthedocs.io/en/latest/configuration.html#custom-background-color-and-custom-text-color).

**Comment by 21st-centuryman** [comment]
@ahrm thank you so much for this software, btw. I hope you are in good health.

I wanted to have everything in a different color when i switch to dark mode as my highlighting is much worse when i have a dark background.

**Comment by ahrm** [comment]
I have already implemented this, but it is not yet available in the public source repo.

**Comment by 21st-centuryman** [comment]
Oh bless. Something to look forward to I guess 😊

Will it be available in the next release?

Also want to personally say your software has made college so much more fun. Again thank you.

**Comment by ahrm** [comment]
> Will it be available in the next release?

Yes.

> 
Oh bless. Something to look forward to I guess 😊

Will it be available in the next release?

Also want to personally say your software has made college so much more fun. Again thank you.
I would love to contribute. Will there be a list of features to implement in the milestones page in the future?

Thanks for the kind words :). The next update will be big and a large portion of code will be changed, so I recommend waiting for that before trying to contribute, because it may be obsolete when the next version comes out otherwise.

**Comment by 21st-centuryman** [comment]
Ok, thank you. 
Good luck and god speed
