### ISSUE TITLE
Keymap for smart move forward, smart move backward

### ISSUE THREAD

**Issue by Euthoniel** [ahrm/sioyek#859]
Hello,

I'm enjoying Sioyek, thanks for making it, but there is something I miss from mupdf. Is it possible to make keys that behave like mupdf's smart move forward/backward?

Basically, the smart move forward key should go to the bottom of the page, but if it is already at the bottom of the page it should go to the top of the next page. Similarly, the smart move backward key should go to the top of the page, but if it is already at the top of the page it should go to the bottom of the previous page.

Thanks!

**Comment by ahrm** [comment]
We have added support for custom javascript functions in the development branch, so such niche functionalities can be implemented by users instead of adding a lot of very niche commands to the core sioyek. You can implement this using something like this:

File `next_page_smart.js` (next to `prefs_user.config`):
```
function get_offset(){
    return JSON.parse(sioyek.get_state_json())[0]["y_offset"];
}

let offset = get_offset();
sioyek.goto_bottom_of_page();
let new_offset = get_offset();

if (new_offset === offset){
    sioyek.next_page();
    sioyek.goto_top_of_page();
}
```

Add this to `prefs_user.config`:
```
new_js_command _next_page_smart next_page_smart.js
```
Now you can bind it to a keybind in `keys_user.config`:
```
_next_page_smart <keybind>
```
