### ISSUE TITLE
"main":  Windows 64 bit build fails - libcurl.lib missing

### ISSUE THREAD

**Issue by ix07** [ahrm/sioyek#861]
Hi.

On my system there is an error  when building the current version from the "main"-branch.

There seems to be an error in the "mupdf"-dependency. When building the 64bit it seems to use the 32 bit version of "libcurl" and then fails to link. When opening the "mupdf.sln"-solution in the IDE the solution does not seem to be correctly configured - there isn't even a 64 bit build configuration for "libcurl".

LINK : fatal error LNK1181: cannot open input file 'D:\ENV\git\sioyek\mupdf\platform\win32\Release\libcurl.lib' [D:\ENV\git\sioyek\mupdf\platform\win32\mupdf-curl.vcxproj]

Building the current version of "mupdf" directly (https://github.com/ArtifexSoftware/mupdf.git) works fine.

Am I missing something?

Used environment:
Windows 10
VS2022  64 bit
QT 5.15.2
Build environment: Qt 5.15.2 (MSVC 2019 64-bit), 

Thanks.

**Comment by smooroodina** [comment]
Same as my environment :) I remember encountering the same error output as you.

I followed the explanation "**Steps for proper build on Windows**" in the last comment on 👉 **this issue[ #143 ]** 👈 and the build was **successful** 👍
It would be better to check that each command step included in the _build_windows.bat_ file is performed without errors. 

I will write down my experience for your reference.

- To follow the comment exactly, do in "**x64 Native Tools Command Prompt for VS 2022**". If you don't want to modify _build_windows.bat_, you can try in "**Developer PowerShell for VS 2022**" but I'm not really sure it will work...

- Don't forget to add **portable** or **non-portable** as an option (otherwise you'll get an error in command line because of the parentheses).

- In my case, building multiple iterations also resulted in new linking errors.
Try deleting the sioyek root directory and starting with the **git clone** step.

- If the build is successful, find "**sioyek.exe**" in the path "_sioyek\sioyek-release-windows_\\" and run it!

----------------------------------------------------------------------------------------------------------------------
**+** 🤔I am of the opinion that the _build_windows.bat_ file of the code should be modified with the **basic command keywords supported by Windows cmd**.
- just like this: [build_windows.bat.txt](https://github.com/ahrm/sioyek/files/13403981/build_windows.bat.txt)

Unix commands (cp, rm) are not supported unless PowerShell is used, and users may repeat incorrect resolution attempts due to unfamiliar error output that is far from the actual cause of build failure. like me :(

----------------------------------------------------------------------------------------------------------------------
Anyway, ix07, I hope I can help if you haven't figured out the solution yourself yet.

**Comment by ahrm** [comment]
This error is not important. We don't use `libcurl` and only use `libmupdf` which will be built correctly.
