### ISSUE TITLE
Feature Request: invert touchpad horizontal scrolling

### ISSUE THREAD

**Issue by iiiian** [ahrm/sioyek#887]
I want to suggest a small improvement here. Currently, the touch pad scrolling behavior is inconsistant. 

- **vertical touch pad scrolling:** the pdf page moves along the direction of the fingers (fingers up page up). 
- **horizontal touch pad scrolling:** the pdf page move along the opposite direction of the fingers (fingers left page right). 

It would be nice to change the behavior of touch pad horizontal scrolling for a consistent experience.

Finally, I want to express my appreciation for such an incredible app. Thank you for your hard work!

**Comment by NightMachinery** [comment]
@ahrm It seems `inverted_horizontal_scrolling` in https://github.com/ahrm/sioyek/issues/637 should solve this problem?
That feature is not in any released builds though? Can you make a new release?

**Comment by onjour** [comment]
I'm having the same issue as @NightMachinery, I'm looking at #637 but I don't understand where I'm supposed to configure this option? 

Indeed, there's no trace of `inverted_horizontal_scrolling`in prefs.config or keys.config so how are we supposed to settle this?

Thank you for your help

**Comment by jenuk** [comment]
Hi @onjour as noted above, the feature is not yet in any release build, so you will have to build sioyek yourself (no clue how I did it back then). Afterwards you can just use the `inverted_horizontal_scrolling` straightforward in the config. Though I will note that I would really appreciate an update of the release -- as I had not had the chance to rebuild sioyek on my current laptop.

**Comment by onjour** [comment]
Hi @jenuk thank you for stopping by. Sorry I've overlooked that it wasn't implemented yet although the issue was closed by the maintainer @ahrm 

So..... I managed to make this work by (I'm more a tinkerer than a developer so forgive me if it's not the right way of doing things):

First I built the app following the instructions of the main repo page

- [ ] _rename your sioyek.app in your applications given that you'll replace it_
- [ ] `setopt PIPE_FAIL PRINT_EXIT_VALUE ERR_RETURN SOURCE_TRACE XTRACE`
- [ ] `git clone --recursive https://github.com/ahrm/sioyek`
- [ ] `cd sioyek`
- [ ] `chmod +x build_mac.sh`
- [ ] `brew install 'qt@5' freeglut mesa harfbuzz`
- [ ] `export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"`
☝️(The above is needed to make =qmake= from =qt= be found. Find the path using =brew info 'qt@5'=.)
- [ ] `MAKE_PARALLEL=8 ./build_mac.sh`
- [ ] `mv build/sioyek.app /Applications/`
- [ ] `sudo codesign --force --sign - --deep /Applications/sioyek.app
`

Then I had to add a boolean parameter `inverted_horizontal_scrolling 1` in the `prefs.config` to make it work (for some odd reason it doesn't work if you put it in your `prefs_user.config`).

- [ ] `echo "inverted_horizontal_scrolling 1" >> /Applications/sioyek.app/Contents/MacOS/prefs.config`

I also agree that it would be great the have this implemented in a future release.

**Comment by Jacinto27** [comment]
Just tried this on windows, didn't work. Very obtuse to have two different scrolling directions for different orientations, makes navigation very sluggish.

**Comment by Jacinto27** [comment]
Just tried this on the latest release on windows, didn't work, really not interested in rebuilding the app. Very obtuse to have two different scrolling directions for different orientations, makes navigation very sluggish.
