### ISSUE TITLE
Slide PDFs Display Two Partial Slides When Jumping to Links

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#888]
In slide PDFs, e.g., PDFs produced using LaTeX Beamer, clicking on a link that takes one to another slide, opens the link in such a way that two slides will be displayed partially:

- [Example Slide PDF](https://files.lilf.ir/tmp/WICPIDNU%20Slides.pdf)

Before:
<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/fd2de079-ed26-47be-bc5c-bd6e312dfd58">

After Clicking on the simulatability bullet point on the top navigation bar:
<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/a9b356a9-3ebc-4db0-a771-9fe8e115b815">

Desired behavior after such a link jump:
<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/97db8d95-c911-49ec-91ef-1f3612bce417">

**Comment by ahrm** [comment]
This is usually the desired behavior but not in in presentations. We do have a presentation mode which can be activated using `toggle_presentation_mode` command. However, there was a bug where clicking on links in presentation mode would sometimes go to the previous page instead which should be fixed in this commit in development branch: https://github.com/ahrm/sioyek/commit/12cd07ce1910d18147fa628b6b121c5fce6c0db6.

**Comment by NightMachinery** [comment]
@ahrm Thanks, the fix works. 

Can something "smart" be done to detect a LaTeX Beamer document? (Or slides in general, though Beamer should probably be easily detectable through metadata?) I don't need/want the presentation mode (I have hotkeys that navigate slides in the normal mode), so just activating the presentation mode is ugly. I also tend to switch between normal papers and slides a lot during my presentations, where I can't just keep turning the presentation mode on and off.

**Comment by ahrm** [comment]
Added an `align_link_dest_to_top` config option in https://github.com/ahrm/sioyek/commit/66e60aa019fbc55f67e5a56d61b978a053af5b22.
