### ISSUE TITLE
[FR] Make Marks and Bookmarks store `x_offset` and `zoom_level`

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#914]
Storing the horizontal location and the zoom level is essential to preserving a particular view. E.g., without the horizontal location, one can even end up on the wrong column in two-column papers.

I have taken a look at the code, and it looks straightforward to add these in. There might be some incompatibility problems when loading JSONs saved using previous versions.

Are there any particular reasons this wasn't done already? States do store this info (see `OpenedBookState`).

The new version of Mark can be:
```
struct Mark {
	char symbol;
	OpenedBookState book_state;

	QJsonObject to_json() const;
	void from_json(const QJsonObject& json_object);
};
```
or we can store `x_offset` and `zoom_level` directly in `Mark`.

**Comment by ahrm** [comment]
I have already implemented this and this will be released with the next version of sioyek.

**Comment by NightMachinery** [comment]
> I have already implemented this and this will be released with the next version of sioyek.

This is not part of the `development` branch?
```
struct Mark : Annotation {
    float y_offset;
    char symbol;

    QJsonObject to_json(std::string doc_checksum) const;
    void from_json(const QJsonObject& json_object);
    void add_to_tuples(std::vector<std::pair<std::string, QVariant>>& tuples) override;
};

/*
    A bookmark is similar to mark but instead of being indexed by a symbol, it has a description.
*/
struct BookMark : Annotation {
    float y_offset_ = -1;
    std::wstring description;

    float begin_x = -1;
    float begin_y = -1;
    float end_x = -1;
    float end_y = -1;

    float color[3] = { 0 };
    float font_size = -1;
    std::wstring font_face;

    AbsoluteDocumentPos begin_pos();
    AbsoluteDocumentPos end_pos();
    AbsoluteRect rect();
    QJsonObject to_json(std::string doc_checksum) const;
    void from_json(const QJsonObject& json_object);
    void add_to_tuples(std::vector<std::pair<std::string, QVariant>>& tuples) override;
    float get_y_offset() const;

    bool is_freetext() const;
    bool is_marked() const;

    AbsoluteRect get_rectangle() const;
};
```

**Comment by ahrm** [comment]
We have visible bookmarks and portals (which store the zoom level), which can be used to achieve similar functionality.

**Comment by ahrm** [comment]
Wait, I thought you were asking for visible bookmarks for some reason. You are right it is not implemented in the current version of sioyek. However, since it introduces incompatibilities with the previous version implementing it should be done carefully as it can potentially introduce a lot of bugs. So I probably will implement it myself at some point when I have the time.

**Comment by ahrm** [comment]
Added offset and zoom level in https://github.com/ahrm/sioyek/commit/e98ff9105d1c9f2088d7a8c29070dfb7f8f233b4. We already have visible bookmarks if you want to bookmark a specific location. Saving zoom_level in bookmarks doesn't make sense because bookmarks are supposed to be device/resolution independent.

**Comment by NightMachinery** [comment]
Thanks, they work great.
