### ISSUE TITLE
Issues with `open_link`: many links missed + segmentation fault upon escaping

### ISSUE THREAD

**Issue by prosoitos** [ahrm/sioyek#917]
I am having 2 issues with `open_link`.

1. In pdfs that have many links in a single screen, `open_link` is not adding labels on many of the links.

Example for this pdf: https://training.westdri.ca/programming/#julia.

At the very top of the pdf (written in LaTeX), each little circle hyperlinks to a section in the pdf. The links work (you can test them with a mouse). Triggering `open_link` only adds labels to a handful of them. Same problem with all pdfs created by the same LaTeX code.

2. Triggering `open_link` and then escaping without following any of the links leads to `segmentation fault (core dumped)`.

**Comment by ahrm** [comment]
This was done because some malformed documents have many overlapping link labels which would make the labels very difficult to read. Added a config option named `hide_overlapping_link_labels` to development branch: https://github.com/ahrm/sioyek/commit/93bee341a5636b4a357b77f63f067e73f65c1a4f

You can now disable this behavior by adding this to `prefs_user.config`:

```
hide_overlapping_link_labels 0
```

The segmentation fault issue should already be fixed in the development branch.
