### ISSUE TITLE
Screenshot-like area-based annotations

### ISSUE THREAD

**Issue by hrdl-github** [ahrm/sioyek#941]
Last year zotero introduced an area-based annotation tool, which allows creating an annotation by selecting a rectangular region. The areas contents are rendered in the annotation sidebar, e.g.

![15 13 54](https://github.com/ahrm/sioyek/assets/31923882/961f670b-9f94-46d3-aea6-a47d0e753c4e)

This is very useful for highlighting / saving parts of a document where text-based annotations would usually fail. Would this be in-scope for sioyek? Displaying an image is not exactly compatible with the text-based nature of sioyek, but this might be relevant for a e.g. markdown/html/json export of annotations.

**Comment by ahrm** [comment]
We already had freetext bookmarks which allowed you to add a text annotations in a box. In https://github.com/ahrm/sioyek/commit/aa4e3d28d503ef2ea8f5f24f199f73b0758a0167 I made it so that if you have a freetext bookmark with text `#`, it will be rendered as a box. You can also change the color by appending a color tag. For example if bookmark is `#r` it will be colored with the same color as `r` highlights. Video:

https://github.com/ahrm/sioyek/assets/6392321/04d6c3e9-2676-4c89-a643-ccad427c5626

**Comment by ahrm** [comment]
It is already included in exported annotations in the latest commit.

**Comment by bragiato** [comment]
Would it be possible to create a command to send the image of the selected area to the clipboard? Thx.

**Comment by ahrm** [comment]
Added a `copy_screenshot_to_clipboard` command inhttps://github.com/ahrm/sioyek/commit/bfe7a216f212ddfbdd410339da4a75e82fec5341.

**Comment by bragiato** [comment]
thx!

**Comment by SuperCowProducts** [comment]
> We already had freetext bookmarks which allowed you to add a text annotations in a box. In [aa4e3d2](https://github.com/ahrm/sioyek/commit/aa4e3d28d503ef2ea8f5f24f199f73b0758a0167) I made it so that if you have a freetext bookmark with text `#`, it will be rendered as a box. You can also change the color by appending a color tag. For example if bookmark is `#r` it will be colored with the same color as `r` highlights. Video:
> 
>  box.mp4

In case anyone forgot the command to activate this is `add_freetext_bookmark`, as shown in the video.
