### ISSUE TITLE
delays in the new_js_command

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#950]
I am trying to add a delay in one of my custom js function.

```
sioyek._extract_highlights();

setTimeout(delete, 10000);


function delete() {

    sioyek.delete_all_highlights();

}
```
`setTimeout`   doesn't seem to work. I also tried to implement  `async` and `await` but they don't work either. Right now I have incorporated the delay in the `delete_all_highlights` function itself. But it would be nicer if I could implement it using the `new_js_command`. Is this a limitation of the `new_js_command` or am I missing something here?

**Comment by ahrm** [comment]
We use Qt's javascript engine which does not have `setTimeout` (it doesn't make sense for Qt since the javascript is usually run synchronously and and timeout would have to block the GUI). However, I added a `wait` command to sioyek in https://github.com/ahrm/sioyek/commit/4f15b8eae7ed7f1c55178571e8250e7ed49192f6. Since this command blocks, it should only be called from async js commands like so, `test.js`:
```
sioyek_async.toggle_dark_mode();
sioyek_async.wait(1000);
sioyek_async.toggle_dark_mode();
```
`prefs_user.config`:
```
new_async_js_command _test_js_command test.js
```

**Comment by nikinbaidar** [comment]
https://github.com/ahrm/sioyek/commit/4f15b8eae7ed7f1c55178571e8250e7ed49192f6 solves the issue. 

Thanks!
