### ISSUE TITLE
Moved to a new computer : lost bookmarks and highlights.

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#977]
Hi,

I just transferred all my data to a new computer. I still have the old `local.db` and `shared.db`. When using the command `export` to generate a `.json` backup, all my highlights and bookmarks are there with correct path on the new computer.

However, when I open the .pdf in Sioyek, I can't find any bookmarks nor highlights when using `gb` or `gh` commands.

Any idea how to solve this issue ?

Thank you very much.

**Comment by ahrm** [comment]
Which version of sioyek are you using? Have you tried opening a file, closing sioyek and opening the file again?

**Comment by Elaws** [comment]
Latest Sioyek commit I have on my fork is https://github.com/ahrm/sioyek/commit/caf5569ae896d1d945ec891dddbd48732a5be475. 

Closing sioyek and opening the file again does not solve the issue. What is weird is that de export *does* contain the highlights and bookmarks.

**Comment by Elaws** [comment]
I could try to do an `import` with the `export` I just generated, but I don't want to overwrite something.

(Another weird point is that I have a backup of the Sioyek folder from January, but when I do the export from that folder, the `.json` does contain a list of files, but not my highlights and bookmarks.)

**Comment by Elaws** [comment]
The exported `.json` shows the proper path, annotations and bookmarks, so not sure why don't they appear in the `gb` and `gh` commands.

**Comment by jinjiaodawang** [comment]
I noticed that Sioyek has recognized the `.db` files after import on a new PC. To debug the issue, why not try adding a new bookmark on the new PC, then export the bookmarks to check if the new bookmark's `checksum` and `path` align with the records? Hope it helps.

**Comment by Elaws** [comment]
@jinjiaodawang 

Thank you. How do you know Sioyek has "recognized" your `.db` files, and what do you mean by 'import on a new PC".

Finally, what would be the next steps weither checksums comply or not ?

**Comment by jinjiaodawang** [comment]
Since the `export` command outputs a `.json` file that contains old bookmarks, but you cannot access those using the `gb` command, I suspect that Sioyek is aware of the old records' existence but does not match the file you opened on the new PC. Therefore, I am interested in seeing that output.

If `path` or `checksum` do not comply, means the bookmarks are not correctly linked to their respective pdf files.

**Comment by Elaws** [comment]
Ok, problem solved. It's stupid : I have 2 versions of the same `.pdf` on my computer, and after misinterpreting the export `.json` structure, I kept opening the version which **didn't** contain the annotations. @ahrm is right that opening the **correct** version **twice** (i.e. closing and reopening Sioyek again).

Sorry about that stupid issue, and thank you very much to both of you !

**Comment by Elaws** [comment]
So this issue is completed, thanks again.

**Comment by mostafatouny** [comment]
For the reference,
- Sioyek computes the md5 hash of pdf files in `local.db` and uses that hash to reference bookmarks, highlights, ..etc in `shared.db`.
- When you open a pdf file with Sioyek for the first time, It computes the md5 hash but does not use it. When you re-open the pdf file for the second time, the hash is used to fetch bookmarks, highlights, ..etc in `shared.db`.
- Importing the json file constructs the `shared.db`. So you can equivalently move `shared.db` to the new computer.
- The hash computed in `local.db` **MUST** match the `checksum` in the exported json file. 
- You can compute the md5 hash locally on your PC. Just google how to compute the md5sum of a pdf file. On Arch we have [md5sum](https://man.archlinux.org/man/md5sum.1.en) package.
- The hash computed manually by you **MUST** match the hash computed by Sioyek.

Moreover, If you modified the pdf file, like changing the table of contents, then the md5 hash is almost likely going to be different. You may modify the hash in the database manually. I find it cleaner to
- backup `local.db` and `shared.db`.
- export to a json file,
- modify `checksum` in the json file, with the manually newly computed md5 hash.
- delete `local.db` and `shared.db` from `~/.local/share/Sioyek`.
- open the modified pdf file twice by sioyek.

**Comment by SuperCowProducts** [comment]
Yeah, unfortunately it must be done with every PDF that had annotations. Wonder if there would be a way to automate this 🤔 

For now, `sqlitebrowser` has been an essential tool for me when a new hash was generated instead of the old one being kept: obviously if the PDF isn't exactly the same there's a risk the annotations won't match to the text / page properly, although for me it went ok, probably because the PDF had barely changed (just set page labels).

In `Browse Data` > `opened_books`, if the PDF has changed slightly it will have a different `path`, but the `document_name` will be the same, so you can batch replace the old `path` with the new one in `highlights` and `bookmarks`.

I was able to get AI to write a script that printed `document_name`s of files with pre-existing `highlights` and `bookmarks` though (this way I only had to open a fraction of the PDFs listed in `opened_books` to be sure all my annotations were searchable in the database again): 

<details>

<summary>
Script
</summary>

```python
#!/usr/bin/python
import sqlite3
import sys

def check_references(db_path):
    """
    Check if every path in opened_books has at least one matching document_path
    in highlights or bookmarks. Print the document_name if true.
    """
    conn = None
    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        # Query to find document_names with matching paths in highlights or bookmarks
        query = """
        SELECT DISTINCT ob.document_name
        FROM opened_books ob
        WHERE EXISTS (
            SELECT 1 FROM highlights h WHERE h.document_path = ob.path
        ) OR EXISTS (
            SELECT 1 FROM bookmarks b WHERE b.document_path = ob.path
        )
        ORDER BY ob.document_name;
        """

        cursor.execute(query)
        results = cursor.fetchall()

        if not results:
            print("No matching documents found.")
        else:
            for row in results:
                print(row)

    except sqlite3.Error as e:
        print(f"Database error: {e}", file=sys.stderr)
    finally:
        if conn:
            conn.close()

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python check_references.py <path_to_sqlite_file>", file=sys.stderr)
        sys.exit(1)
    check_references(sys.argv[1])
```

</details>

If the file did *not* change, you can look up where it is after generating md5 hashes for all your PDFs (I ran this command in the directory I knew all my PDFs would be in, it only took like a minute which is super fast considering the output file ended up having almost 20.000 lines!)
```bash
fd -e pdf -x md5sum {} + > pdf_checksums.txt
```
